### ISSUE TITLE
How to set up many sites in vccw?

### ISSUE THREAD

**Issue by minthemiddle** [vccw-team/vccw#101]
I am considering switching from DesktopServer to VCCW. I have many Wordpress projects and would like to have them in one instance of VCCW. Unfortunately I could not find any reference on how to do that.

How can I do that? Can I add more than one `hostname` in `site.yaml`? And should I just create one table per site in the global MySQL database?

How do you handle these multiple sites in VCCW?

**Comment by miya0001** [comment]
Virtual host isn't supported on VCCW.
If you can write a shell script, please write setup script into the `provision-post.sh`.

**Comment by mehh** [comment]
I can probably put something together.  Will check back later.

**Comment by minthemiddle** [comment]
@mehh Did you already come up with an idea? VCCW would be such a good alternative to VVV if it supported multiple instances in one box.

**Comment by andresabello** [comment]
You can just set up multiple instances of vccw.
1. Unzip the zip file to you projects folder. 
2. Go to default.yml
3. Change both the domain and IP address. This cannot be the same as any of your other instances. 
4. Vagrant up and you should be good to go.

**Comment by designweb** [comment]
I have managed to get multiple sites working in vccw but they all use the same database. 
The only thing I can see in the vagrantfile that refs mysql is this:
:mysql => {
        :bind_address           => '0.0.0.0',
        :server_debian_password => 'wordpress',
        :server_root_password   => 'wordpress',
        :server_repl_password   => 'wordpress'
      },

Not sure how to set up a new db, any ideas?

**Comment by andresabello** [comment]
On your command line go to the virtulbox (vagrant up) 
Then login to mysql and use the commands to create a new one.
http://www.liquidweb.com/kb/create-a-mysql-database-on-linux-via-command-line/
Or install an sql gui like workbench for windows or sequelpre fpr mac

**Comment by designweb** [comment]
Thanks for the reply but could you explain it in more detail. I'm not even sure how to login to mysql. Sorry I am new to vagrant and virtualbox. I am on a Mac.
I have sequel pro, but not sure how to connect via that either.
Thanks in advance

**Comment by fpaeslima** [comment]
@designweb 

## Create a new database for your new wordpress site in VCCW:

#### 1. With your box running, ssh to your Vagrant Box.
```shell
$ vagrant ssh
                   ___           ___           ___
      ___         /  /\         /  /\         /__/\
     /__/\       /  /:/        /  /:/        _\_ \:\
     \  \:\     /  /:/        /  /:/        /__/\ \:\
      \  \:\   /  /:/  ___   /  /:/  ___   _\_ \:\ \:\
  ___  \__\:\ /__/:/  /  /\ /__/:/  /  /\ /__/\ \:\ \:\
 /__/\ |  |:| \  \:\ /  /:/ \  \:\ /  /:/ \  \:\ \:\/:/
 \  \:\|  |:|  \  \:\  /:/   \  \:\  /:/   \  \:\ \::/
  \  \:\__|:|   \  \:\/:/     \  \:\/:/     \  \:\/:/
   \__\::::/     \  \::/       \  \::/       \  \::/
       ~~~~       \__\/         \__\/         \__\/

http://vccw.cc/

Initial code by Takayuki Miyauchi.
https://github.com/miya0001
[vagrant@yourboxname ~]$ 

```
#### 2. Ok, now you're inside your server/box, let's enter the mysql as root
```shell
[vagrant@yourboxname ~]$ mysql -u root -p
```
Enter your password: **wordpress**
```shell
[vagrant@yourboxname ~]$ mysql -u root -p
Enter password:
```
#### 3. Now we're using mysql as root user let's check our dabatases (don't forget the semicolon)
```shell
mysql> show dabatases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| test               |
| wordpress          |
| wordpress_test     |
| wp-test            |
+--------------------+
7 rows in set (0.09 sec)

```

#### 4. Create a new database
```shell
mysql> create database db_example;
Query OK, 1 row affected (0.05 sec)

```

#### 5. Get out of your mysql session and your box/server
```shell
//exit mysql typing exit
mysql> exit
Bye
//exit vagrant ssh typing Ctrl+D
youruser@yourenvironment $ 

```

#### 6. Go to your site **www/wordpress/wp-config** file
```php
// ** MySQL settings ** //
/** The name of the database for WordPress */
define('DB_NAME', 'db_example');

/** MySQL database username */
define('DB_USER', 'root');

```

That's it, next time your access **yoursite.dev** or whatever your URL is, you'll be asked for desired language and basic wordpress configuration like user, password, email etc. You can keep the same pattern as vccw for consistency purposes.

user: admin
password: admin

I hope this can help you. Cheers
