### ISSUE TITLE
Php error on customize page

### ISSUE THREAD

**Issue by FerreiraRaphael** [vccw-team/vccw#102]
It should not be bug, but i installed the vccw perfectly, and every thing its ok, but i'm getting this php error in the customize page. 

![captura de tela_2016-03-08_17-36-09](https://cloud.githubusercontent.com/assets/11987481/13615501/6279cc18-e554-11e5-8dc6-fa58859c604b.png)

Can you help me ?

**Comment by miya0001** [comment]
Please deactivate plugin `Dynamic Hostname`.

**Comment by FerreiraRaphael** [comment]
Sorry @miya0001, i just removed the vm, and installed again and the error stopped, can't reproduce the error again

**Comment by quig** [comment]
Happened to me as well. When I deactivate `Dynamic Hostname`, I loose my admin interface as follow:

![image](https://cloud.githubusercontent.com/assets/3135312/13947986/ddd11528-f01d-11e5-9c97-fb7b19b8d4ad.png)

Btw, I am unable to connect to vccw.dev even with the plugin activated.

**Comment by miya0001** [comment]
Please visit http://vccw.dev/ .
http://vccw.cc/#h2-2
