### ISSUE TITLE
Multisite install limits upload size to 1MB

### ISSUE THREAD

**Issue by followfung** [vccw-team/vccw#104]
When set up the site.yml file to do a multi-site install, it limits the upload to 1MB.  I have to go into Network Settings and change the max upload file size manually.

Is there a way to set this up using the Vagrant configuration?

**Comment by miya0001** [comment]
Use provision-post.sh.

http://vccw.cc/#h2-5

**Comment by followfung** [comment]
Thanks!

Would you happen to know the correct setting to change this? I've been trying to update fileupload_maxk with no success. The setting in the WP admin remains the default (1500)

```
# vagrant output
==> vccw.dev: Success: Added 'fileupload_maxk' option.
```

```
# provision-post.sh
/usr/local/bin/wp --path=/var/www/wordpress option add fileupload_maxk 32000 --allow-root
```

**Comment by torounit** [comment]
@followfung 

Please Try

```
# provision-post.sh
/usr/local/bin/wp --path=/var/www/wordpress network meta update 1 fileupload_maxk 40000
```

http://wp-cli.org/commands/network/meta/

**Comment by followfung** [comment]
Works! It would be awesome if it could be baked into the cookbook though!
