### ISSUE TITLE
Using public network on fixed IP address

### ISSUE THREAD

**Issue by youthkee** [vccw-team/vccw#106]
I want to check the VCCW environment from mobile devices through Wi-Fi network.
So, I change an option in the Vagrantfile as blow, referring [this article](http://big1to.com/development-note/828).

site.yml
```
hostname: tsumugi.local
ip: 192.168.33.13
```

Vagrantfile
```
config.vm.network :public_network, ip: _conf['ip']
```

But, when I ran "vagrant up", there occurred errors as blow, and couldn't access by hostname or fixed IP address(written in site.yml) both in browsers.

```
SIOCADDRT: Network is unreachable

The SSH command responded with a non-zero exit status.
```

So, I tried again with an option just as blow.

Vagrantfile
```
config.vm.network :public_network
```

And I looked up IP address by ssh commands.

```
ifconfig | grep "inet addr"
inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
inet addr:192.168.11.8  Bcast:192.168.11.255  Mask:255.255.255.0
inet addr:127.0.0.1  Mask:255.0.0.0
```

By this way, I could access the VCCW environment as `192.168.11.8` in both PC and mobile browsers.

Is there the way to access by fixed IP address or hostname through Wi-Fi network?
Or, is there something wrong with my settings?

My environments are here.

Mac OS 10.10.5
VirtualBox 5.0.14
Vagrant 1.8.1

**Comment by miya0001** [comment]
See https://www.vagrantup.com/docs/networking/public_network.html.

But I though you shouldn't make VCCW public, because firewall is disabled on it.
So you should use `vagrant share` or `ngrok`.

* https://www.vagrantup.com/docs/cli/share.html
* https://ngrok.com/

**Comment by youthkee** [comment]
Thank you!
I tried Vagrant Share and it works well :smile:

**Comment by youthkee** [comment]
After that, I tried Vagrant Share with multisite setting again, and I failed with the error below.
Is there anyone who occurred the same error, or knowing the solution about this?

```
Vagrant was unable to detect an HTTP port for your machine.

Your Vagrant machine is reporting that it is accessible at
the address: '192.168.33.13'.

Vagrant tries some common HTTP ports to try to find a listening
HTTP server, but all the attempts failed. There are a few options
to fix this error:

  1. Turn off HTTP sharing with the `--disable-http` flag.

  2. Have your HTTP server listen on port 80, 3000, 4567, 8000,
     or 8080. Vagrant will automatically try these.

  3. Specify an HTTP port explicitly to vagrant share with the
     `--http` flag.

  4. Make sure that the address above along with your HTTP port
     are accessible from this machine. Sometimes firewalls or
     binding to the wrong IP cause it to become inaccessible.
```
