### ISSUE TITLE
Triggering XDebug

### ISSUE THREAD

**Issue by chrispage1** [vccw-team/vccw#108]
So xdebug has now been added to VCCW as per Issue #79 but how do I trigger debugging? I have modified xdebug.ini to include the following to allow for debugging - 

```
xdebug.remote_enable=true
xdebug.remote_port=9000
xdebug.profiler_enable=true
xdebug.idekey=VCCWDEBUG
xdebug.remote_connect_back=true
xdebug.remote_autostart=true
```

Can this be added?

Chris.

**Comment by miya0001** [comment]
Oh, OK please wait a couple of days.

**Comment by chrispage1** [comment]
@miya0001 Thank you!
