### ISSUE TITLE
after "vagrant resume" lost wp-admin data

### ISSUE THREAD

**Issue by tom0910** [vccw-team/vccw#109]
Hi,
I did "vagrant suspend" and "vagrant resume"
The later one seems to me doing provision. Wordpress in a starting state. I mean all the theme settings are gone, wordpress admin lost all the settings, like a fresh new wordpress install

Cheers, Tamas

**Comment by flurinduerst** [comment]
I think this is because in `site.yml` the default option is to reset the database on provisioning. I personally like to set this option to false:

```
#
# DB will be reset when provision
#
reset_db_on_provision: false
```
