### ISSUE TITLE
Can't follow install process described on http://vccw.cc/ (ubuntu 15.10)

### ISSUE THREAD

**Issue by eric-burel** [vccw-team/vccw#110]
Hi,

The installation process does not work as expected on ubuntu 15.10. Everything works fine, until I try the vagrant up command.
It blocks on the message 
`==> vccw.dev: Waiting for machine to boot. This may take a few minutes...
vccw.dev: SSH address: 127.0.0.1:2222
    vccw.dev: SSH username: vagrant
    vccw.dev: SSH auth method: private key
`
and then time out.

I  activated manually the GUI adding the line   vb.gui = true
in the conf file (see http://stackoverflow.com/questions/22575261/vagrant-stuck-connection-timeout-retrying) and noticed that centos (in the virtual box) ask me to login. So, after a few try, I figured out that username and pass are both "vagrant". Then I have a nice message on the virtual machine, but I still don't now what to do and it still eventually time out on ubuntu. (Note that the keyboard is qwerty by default, I did not manage to set it in azerty).

I can't connect to either http://vccw.dev/ or http://192.168.33.10/ .

So, I probably missed something, but what ?
Edit : I seem to have the same issue when following this install : http://www.hongkiat.com/blog/install-wordpress-locally-vagrant/

**Comment by miya0001** [comment]
I'm sorry to be late. 😓 

It looks caused by network or performance problem.
But I'm sorry I haven't figure it out about it...

Can you provision VVV?
https://github.com/Varying-Vagrant-Vagrants/VVV
