### ISSUE TITLE
Install mcrypt

### ISSUE THREAD

**Issue by chrispage1** [vccw-team/vccw#115]
Hi,

Would it be possible to install mcrypt when VCCW is provisioned or at least add an option to make this easy to automatically deploy? We use mcrypt encryption techniques for a lot of our WP builds.

Thanks,
Chris.

**Comment by miya0001** [comment]
👍

**Comment by miya0001** [comment]
https://github.com/vccw-team/vccw/commit/65cf6bc0c3910e24d44bc911a5888ad98aba4029

**Comment by miya0001** [comment]
I have an advice. 😄 
You can use `provision-post.sh` like following.

```
#!/usr/bin/env bash

set -ex

sudo yum install package-that-you-want-to-install
/usr/local/bin/wp --path=/var/www/wordpress plugin install contact-form-7 --activate
```
http://vccw.cc/#h2-5

**Comment by chrispage1** [comment]
Great thank you for your help and quick response!
