### ISSUE TITLE
ideal Virtual Machine Settings

### ISSUE THREAD

**Issue by flurinduerst** [vccw-team/vccw#116]
Hi, how should the Virtual Machine Settings in site.yml be configured depending on your machine. Should it match the pc specific components? i.e. if I have a quad core with 8GB Ram, should I configure it like this? 

```
#
# Virtual Machine Settings
#
memory: 8192
cpus: 4
```

**Comment by miya0001** [comment]
> Should it match the pc specific components?

Sorry I haven't figure it out about it. I did benchmark for a couple of times, but I could't find improvement.
So you shouldn't mind about I think you should use default. 😄
