### ISSUE TITLE
ideal plugin management

### ISSUE THREAD

**Issue by flurinduerst** [vccw-team/vccw#117]
What's the ideal procedure to manage plugins? 
Do you edit the `plugin` option in `site.yml` and update those with provisioning (composer alike)? 
Or would you suggest to manage plugins in the backend manually?

In general I'm asking myself when to `vagrant reload --provision`? Is vccw meant to only vagrant up as setup and then never provision? Are the plugin entries in `site.yml` meant as "setup wordpress with those plugins pre-installed" or this this a library of plugins that gets updated from time to time?

btw: how can i prevent vccw from installing `Akismet` and `Hello Dolly` ?

**Comment by miya0001** [comment]
Please try `vagrant provision` or `vagrant reload --provision`, but if you are in a hurry you can use wp-cli.
The chef based provisioner of VCCW will be always executed when run `vagrant up` and `vagrant provision`.

> how can i prevent vccw from installing Akismet and Hello Dolly ?

Those plugins are contained in WordPress packages, so you should remove them when proision like following.

`./provision-post.sh`:

```
#!/usr/bin/env bash

set -ex

/usr/local/bin/wp --path=/var/www/wordpress plugin delete akismet
/usr/local/bin/wp --path=/var/www/wordpress plugin delete hello-dolly
```
http://vccw.cc/#h2-5

**Comment by flurinduerst** [comment]
great! thanks a lot!

**Comment by flurinduerst** [comment]
Thanks for you response. Nice to know! :)  So you do not recommend using the «Plugin» panel in the WordPress-Backend to add/remove Plugins?

**Comment by miya0001** [comment]
I don't say "not recommended". It's ok to use that. 😄 
But I feel wp-cli is more useful.

Please try following.

```
$ vagrant ssh -c "wp plugin list"
```
