### ISSUE TITLE
reason behind the "wordpress" folder

### ISSUE THREAD

**Issue by flurinduerst** [vccw-team/vccw#119]
I really start to love using vccw. I think this is a great box for fast-paced websites. Thanks!

I'm asking myself why the default path is `var/www/wordpress` and not simply `var/www`? Wouldn't this mirror a server environment better?

I've seen that `www` contains the following:

```
cgi-bin
error
html
icons
wordpress
```

what's the purpose os the folders `error`, `html` and `icons` ?

**Comment by miya0001** [comment]
Those folders are created by Apache.
VCCW doesn't need them.
But If you delete those directories, you may not be able to restart apache.
(I haven't tried yet. 😄 )

**Comment by flurinduerst** [comment]
I see, thanks. Still wondering why the default path is var/www/wordpress and not simply var/www?
