### ISSUE TITLE
how to push/pull db with wordmove?

### ISSUE THREAD

**Issue by flurinduerst** [vccw-team/vccw#120]
when trying to execute the command `wordmove push -d` on the bare machine i get `mysqldump: command not found`

I tried to see what happens when executing it on the VM:

`vagrant ssh`
`cd ../../var/www/`
`wordmove push -d`

as `www` only contains `cgi-bin`, `error`, `html`, `icons` and `wordpress`(so the `Movefile` is not synced to the VM), I get the error `fetch_movefile: Could not find a valid Movefile`

How is this done? Am I missing something?

**Comment by miya0001** [comment]
You have to install `mysqldump` to the remote server.

**Comment by raulillana** [comment]
Hi. Try this @flurinduerst :

```
vagrant ssh
cd /vagrant
wordmove push -d
```
