### ISSUE TITLE
PhpMyAdmin

### ISSUE THREAD

**Issue by dnagyelek** [vccw-team/vccw#124]
Can I somehow add phpmyadmin to the host ?

**Comment by tuckQ** [comment]
Here is what I did.
1. Download phpMyAdmin package from the official site.
2. Place the unzipped phpMyAdmin folder into /vagrant/www/wordpress
3. Access http://192.xxx.xx.xx/phpmyadmin

**Comment by jonnycyr** [comment]
Hello, I tried following what you did - I do not have a www folder. Instead my folder structure is vccw/wordpress. I copied the unzipped phpMyAdmin folder into there but it still doesn't work, any suggestions?

**Comment by tuckQ** [comment]
I looked into it, but I could not figure out why it is not working. Since this thread is closed already, you might want to create a new thread and ask for suggestions from other users.

**Comment by adionditsak** [comment]
You can add phpmyadmin in a simple way (without configuration), by installing aptitude, update/upgrade packages with apt, install phpmyadmin and move installed files into your web root:
https://github.com/BetterCollective/bc-wordpress-development/commit/3beb88201a713183be45b6290d771227915d668f
