### ISSUE TITLE
Vagrant up error

### ISSUE THREAD

**Issue by tuckQ** [vccw-team/vccw#133]
After I updated php version by installing remi package from the repository bellow,

`http://rpms.famillecollet.com/enterprise/remi-release-6.rpm`

I started getting the bellow error upon vagrant up.

`The box chef/centos-6.5-i386 could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
"vagrant login". Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/chef/centos-6.5-i386"]
Error: The requested URL returned error: 404 Not Found`

Does anyone know how to solve this problem?
Any suggestions will be appreciated. Thanks!

**Comment by miya0001** [comment]
"Chef" was changed to the "Bento", so you have to use "bento/centos-6.5-i386".
https://atlas.hashicorp.com/bento/boxes/centos-6.7-i386

**Comment by tuckQ** [comment]
Thank you for your input. I installed "bento/centos-6.5-i386" and solved vagrant up error successfully.

However, I came across another problem upon vagrant provision and received an error "Chef never successfully completed! Any errors should be visible in the output above. Please fix your recipes so that they properly complete." 

It seems like the origin of the error is "Error executing action `install` on resource 'package[php-mysql]'"

Do you have any idea how to solve this error? 

I appreciate for your advice. Thanks!

**Comment by miya0001** [comment]
Are you a windows user?
Chef cookbook has to be UTF-8 + LF, because cookbooks will be executed in the Guest Machine.
Please check your cookbook's encoding.

**Comment by tuckQ** [comment]
Thanks a lot for another advice! I use Mac OS X. I am not too familiar with Chef and can't figure out what I am supposed to  do. Maybe I will learn how Chef works first and see I will be able to find a workaround.
