### ISSUE TITLE
VirtualHost support

### ISSUE THREAD

**Issue by miya0001** [vccw-team/vccw#147]
Vagrantfile:

``` ruby
  if File.exists?(File.join(File.dirname(__FILE__), 'virtualhosts.yml')) then
    config.vm.provision "ansible_local" do |ansible|
      ansible.extra_vars = {
        vccw: _conf
      }
      ansible.playbook = "provision/playbook-virtualhost.yml"
    end
  end
```

**Comment by miya0001** [comment]
Ah, we have to add hosts to `/etc/hosts`, so it has to be executed before hosts_updater.

**Comment by torounit** [comment]
@miya0001 How about hostsupdater.aliases ?

**Comment by miya0001** [comment]
If we have many virtual hosts in the guest machine and the machine will be aborted, I don't have any idea to restore it.
