### ISSUE TITLE
(V3) wp-content/upload write permissions

### ISSUE THREAD

**Issue by retani** [vccw-team/vccw#160]
After 'vagrant up' of vccw-3.0.0-beta1, i wasn't able to upload an image to wordpress (apache has no write permission to wp-content/upload). I fixed it by changing Vagrantfile line 60. Did not fork because I am not sure if this is a good way, but may be an inspiration:

```
config.vm.synced_folder _conf['sync_folder'],
      _conf['document_root'], :create => "true", :mount_options => ['dmode=775', 'fmode=664'], owner: "www-data", group: "www-data"
```

BTW I never could make v2 work, but this one works just fine. Thanks!

**Comment by miya0001** [comment]
Thanks!

**Comment by SidaliNadji** [comment]
THX +1
