### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by Storm-Engineer** [vccw-team/vccw#161]
Current instructions are unclear and confusing for people who don't have past experience with vagrant and/or who have certain issues with processing instructions.

EXAMPLE: I was just setting up my first VCCW. I've been working with WP, local servers and remote servers before as well as PHP code and databases but I've never touched Vagrant or Virtualbox or any other sort of local staging solution before so all I could rely on was your instructions.

Sadly I found them to be unclear and confusing, especially for someone like me who is a very literal thinker (due to slight autism) in addition to being inexperienced in the use of vagrant - I couldn't make sense of them and had to ask a friend to help decipher.

1; Step 5 instructs me to download an archive, but then there is no further mention of it. You don't tell me to extract it to the directory I will want to use for my development. I was wondering what was the point of that download when there are no further instructions regarding the archive.

2; Step 6 says "cd to a new directory". What new directory? New compared to what - wait, what directory was I supposed to be in until now? Since it says _A_ new directory and not _THE_ new directory (nor did it mention extracting the zip) it sounds like I'm just creating a new directory... somewhere? Sure the command next gives a clue but at that point I was totally confused already.

I understand a seasoned developer may find these instructions good enough, but for people who are new to this, and/or have difficulties similar to mine, they don't work well. I suggest some rewording and expanding.

I'm not saying to make it intelligible even for my grandma, but just to don't leave steps and explanations to the imagination or assume the reader will know. For example: "Extract the archive where you wish your work directory to be and cd into it" works much better.

**Comment by miya0001** [comment]
I am sorry for poor documentation.
We always try to improve documentation, but English is the second language for us.
So if you can help with improving documentation, we are very happy.

There is a repository of the main site.
If you have a moment, I am hoping you could send a pull request.
https://github.com/vccw-team/vccw.cc

Thanks!
