### ISSUE TITLE
Fail to install composer libraries

### ISSUE THREAD

**Issue by waviaei** [vccw-team/vccw#172]
On version 3, I am stating to get this error. 

---

TASK [Install Composer libraries] **********************************************
failed: [vccw.dev] (item=hirak/prestissimo:*) => {"changed": true, "cmd": "/bin/bash -lc \"composer global require 'hirak/prestissimo:*'\"", "delta": "0:00:00.051527", "end": "2016-10-24 16:36:31.300057", "failed": true, "item": "hirak/prestissimo:*", "rc": 127, "start": "2016-10-24 16:36:31.248530", "stderr": "/bin/bash: composer: command not found", "stdout": "", "stdout_lines": [], "warnings": []}
failed: [vccw.dev] (item=phpunit/phpunit:*) => {"changed": true, "cmd": "/bin/bash -lc \"composer global require 'phpunit/phpunit:*'\"", "delta": "0:00:00.047217", "end": "2016-10-24 16:36:31.518591", "failed": true, "item": "phpunit/phpunit:*", "rc": 127, "start": "2016-10-24 16:36:31.471374", "stderr": "/bin/bash: composer: command not found", "stdout": "", "stdout_lines": [], "warnings": []}
failed: [vccw.dev] (item=squizlabs/php_codesniffer:*) => {"changed": true, "cmd": "/bin/bash -lc \"composer global require 'squizlabs/php_codesniffer:*'\"", "delta": "0:00:00.048257", "end": "2016-10-24 16:36:31.738898", "failed": true, "item": "squizlabs/php_codesniffer:*", "rc": 127, "start": "2016-10-24 16:36:31.690641", "stderr": "/bin/bash: composer: command not found", "stdout": "", "stdout_lines": [], "warnings": []}
failed: [vccw.dev] (item=wp-coding-standards/wpcs:*) => {"changed": true, "cmd": "/bin/bash -lc \"composer global require 'wp-coding-standards/wpcs:*'\"", "delta": "0:00:00.049439", "end": "2016-10-24 16:36:31.959634", "failed": true, "item": "wp-coding-standards/wpcs:*", "rc": 127, "start": "2016-10-24 16:36:31.910195", "stderr": "/bin/bash: composer: command not found", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/vagrant/provision/playbook.retry

PLAY RECAP *********************************************************************
vccw.dev                   : ok=12   changed=1    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by miya0001** [comment]
Is it beta5?
https://github.com/vccw-team/vccw/releases/tag/3.0.0-beta5

Composer sometimes gets a problem, but it will be ignored and VCCW will continue provisioning on the latest beta release.

**Comment by waviaei** [comment]
No, it was this:
https://github.com/vccw-team/vccw/archive/v3.zip

Will try again with beta 5.

**Comment by waviaei** [comment]
Checked with beta 5 2~3 times, and I confirm this error do not occur.

Off topic (but related to beta5) quick question:
How do I set `multisite_options: {}` to true? I tried `multisite_options: true`, but this ends in error. `multisite_options: { 'true' }` do not work either.

**Comment by miya0001** [comment]
> How do I set multisite_options: {} to true? I tried multisite_options: true, but this ends in error.
> multisite_options: { 'true' } do not work either.

Thanks! I'll try and fix it. 😄

**Comment by waviaei** [comment]
Ah, ok. It might be a bug then. I will close this issue and create a new separate one.
Thanks!
