### ISSUE TITLE
provision-post.sh and playbook-post.yml in the ~/.vccw/conifg

### ISSUE THREAD

**Issue by miya0001** [vccw-team/vccw#173]
Some people are hoping to customize every guest machine.
Allow to run additional provisioner when `~/.vccw/config/provision-post.sh` exists.

But additional ansible based provisioner should be `ansible` not `ansible_local`.

**Comment by miya0001** [comment]
fixed

**Comment by mrhead** [comment]
@miya0001 There is an inconsistency between the documentation and the Vagrantfile. [The documentation](http://vccw.cc/#h2-5) is mentioning `provision-post.yml` but `Vagrantfile` is looking for `playbook-post.yml`.

Which one should be correct?
