### ISSUE TITLE
VBoxManage error

### ISSUE THREAD

**Issue by GTP95** [vccw-team/vccw#180]
While booting the vm I get the following error:
==> vccw.dev: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "6af80a8e-b8a9-4618-b523-d753ec2ae04a", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'vccw.dev' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

My OS is Netrunner rolling (based on manjaro/Arch Linux) and according to pacman everything is up to date:
Vagrant version: 1.8.6-2
VirtualBox version: 5.1.8-1

What can I do?

**Comment by miya0001** [comment]
We are developing v3.
Could you try v3 beta?

https://github.com/vccw-team/vccw/releases

**Comment by GTP95** [comment]
Just tried with vccw-3.0.0-beta5 and got the same error:
==> vccw.dev: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "2d0c16d6-027e-4873-a551-0daec83de1e6", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'vccw.dev' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

**Comment by GTP95** [comment]
I had problems starting another VM in VirtualBox so it's likely a problem with my installation of VirtualBox. I'm trying to fix it.

**Comment by GTP95** [comment]
It was an incompatibility with my kernel/kernel modules. Fixed intalling new kernel. Would you advice me to use the "stable" version or to stick with the beta?
Thanks for your time

**Comment by miya0001** [comment]
Please try Beta. 😄
