### ISSUE TITLE
Can't download new box

### ISSUE THREAD

**Issue by raulillana** [vccw-team/vccw#183]
Hi again team!

You're doing an awesome work as far as i can see… :) :+1: 

I've an error installing the new box, probably a 404/403 problem.

```
$ vagrant box add vccw-team/xenial64
The box 'vccw-team/xenial64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/vccw-team/xenial64"]
Error: 
```

I've tried to login into Atlas, and also like this: `$ vagrant box add vccw-team/boxes/xenial64` but same result. :(

Any clues?

Best regards!

**Comment by miya0001** [comment]
It is a bug of the Vagrant.
Please downgrade Vagrant from 1.8.7 to 1.8.6.

https://github.com/mitchellh/vagrant/issues/7969

**Comment by raulillana** [comment]
Oh, I see, thanks for the quick heads up!
