### ISSUE TITLE
WordPress Import

### ISSUE THREAD

**Issue by timbroadwater** [vccw-team/vccw#187]
Operating System: Windows 10
Vagrant Version:  1.8.4
Virtual Box Version: 5.0.28

This may be a feature request, or just a question, but I'm unable to use Tools/Import/WordPress to import a XML file from another WordPress site (to pull in posts, pages, comments, custom fields, categories, and tags).

Is there something I'm missing in the instructions, because all I get when I click on 'Run importer' with a valid XML file is "Sorry, there has been an error."

**Comment by miya0001** [comment]
Please add the following line to `site.yml`.

```
theme_unit_test: true
theme_unit_test_uri: /vagrant/import-data.xml
```

Your import file has to be in the same directory with `Vagrantfile`, and the file name has to be `import-data.xml`.

Then run `vagrant provison`.

http://vccw.cc/#h2-4
