### ISSUE TITLE
Wordmoved Multisite install in a folder working with Subdomains

### ISSUE THREAD

**Issue by raulillana** [vccw-team/vccw#188]
Operating System: Mac OS Sierra
Vagrant Version: 1.8.7
Virtual Box Version: 5.0.28
VCCW Version: 2.21.0 and 3.0.2
Others: dnsmasq + wildcard DNS

I'm trying to get to work a wordmoved multisite install in a folder working with subdomains (country domain extensions).
This means the subdomain is the same, but the language domain extension defines the child blog site.
Like: sub.domain.com / sub.domain.es / sub.domain.de…

As i can see, wordmove does not support multisite any more, but still works for directory installs and has an open PR to fix them even more.

If there isn't a way to do this with VCCW and Wordmove actually or soon, what's the alternative?  :weary:

**Comment by miya0001** [comment]
Sorry, I don't have any idea, but I will keep open this issue for a while.
