### ISSUE TITLE
mailcatcher failing to get provisioned by ansible

### ISSUE THREAD

**Issue by dheerajbhaskar** [vccw-team/vccw#192]
Operating System: win 10 pro x64
Vagrant Version: 1.9.0
Virtual Box Version: 5.1.10

console log:
>vagrant up
Bringing machine 'vccw.dev' up with 'virtualbox' provider...
==> vccw.dev: Importing base box 'vccw-team/xenial64'...
==> vccw.dev: Matching MAC address for NAT networking...
==> vccw.dev: Checking if box 'vccw-team/xenial64' is up to date...
==> vccw.dev: A newer version of the box 'vccw-team/xenial64' is available! You currently
==> vccw.dev: have version '20161024'. The latest is version '20161209'. Run
==> vccw.dev: `vagrant box update` to update.
==> vccw.dev: Setting the name of the VM: vccw.dev
==> vccw.dev: Clearing any previously set network interfaces...
==> vccw.dev: Preparing network interfaces based on configuration...
    vccw.dev: Adapter 1: nat
    vccw.dev: Adapter 2: hostonly
==> vccw.dev: Forwarding ports...
    vccw.dev: 22 (guest) => 2222 (host) (adapter 1)
==> vccw.dev: Running 'pre-boot' VM customizations...
==> vccw.dev: Booting VM...
==> vccw.dev: Waiting for machine to boot. This may take a few minutes...
    vccw.dev: SSH address: 127.0.0.1:2222
    vccw.dev: SSH username: vagrant
    vccw.dev: SSH auth method: private key
    vccw.dev:
    vccw.dev: Vagrant insecure key detected. Vagrant will automatically replace
    vccw.dev: this with a newly generated keypair for better security.
    vccw.dev:
    vccw.dev: Inserting generated public key within guest...
    vccw.dev: Removing insecure key from the guest if it's present...
    vccw.dev: Key inserted! Disconnecting and reconnecting using new SSH key...
==> vccw.dev: Machine booted and ready!
==> vccw.dev: Checking for guest additions in VM...
==> vccw.dev: [vagrant-hostsupdater] Checking for host entries
==> vccw.dev: [vagrant-hostsupdater] Writing the following entries to (C:/WINDOWS/system32/drivers/etc/hosts)
==> vccw.dev: [vagrant-hostsupdater]   192.168.33.10  vccw.dev  # VAGRANT: 4302bd7c6e8fbfb038acbf63f363b45d (vccw.dev) / 3fe0e94e-e548-4c4c-8c83-2e3e9bc6d05f
==> vccw.dev: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
==> vccw.dev: Setting hostname...
==> vccw.dev: Configuring and enabling network interfaces...
==> vccw.dev: Mounting shared folders...
    vccw.dev: /vagrant => C:/my-home/WebStormProjects/vccw-wordpress-vagrant
    vccw.dev: /var/www/html => C:/my-home/WebStormProjects/vccw-wordpress-vagrant/wordpress
==> vccw.dev: Running provisioner: ansible_local...
    vccw.dev: Running ansible-playbook...

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [vccw.dev]

TASK [Place a ~/.bash_profile] *************************************************
changed: [vccw.dev]

TASK [Place a ~/.bash.d/] ******************************************************
changed: [vccw.dev]

TASK [Place a ~/.bash.d/vccw.sh] ***********************************************
changed: [vccw.dev]

TASK [Download the Composer] ***************************************************
changed: [vccw.dev]

TASK [Run the Composer installer] **********************************************
changed: [vccw.dev]

TASK [Create a ~/.composer/] ***************************************************
changed: [vccw.dev]

TASK [Place a composer.json] ***************************************************
changed: [vccw.dev]

TASK [Install Composer libraries] **********************************************
changed: [vccw.dev] => (item=hirak/prestissimo:*)
changed: [vccw.dev] => (item=phpunit/phpunit:*)
changed: [vccw.dev] => (item=squizlabs/php_codesniffer:*)
changed: [vccw.dev] => (item=wp-coding-standards/wpcs:*)

TASK [Install the WP-CLI] ******************************************************
changed: [vccw.dev]

TASK [Create a ~/.wp-cli/] *****************************************************
changed: [vccw.dev]

TASK [Create a `~/.wp-cli/config.yml` on the Guest] ****************************
changed: [vccw.dev]

TASK [Create a `/vagrant/wp-cli.yml`] ******************************************
ok: [vccw.dev]

TASK [Install WP-CLI packages] *************************************************
changed: [vccw.dev] => (item=vccw/wp-cli-scaffold-movefile:@stable)

TASK [Setup a bash completion for the WP-CLI] **********************************
changed: [vccw.dev]

TASK [Place a ~/.gemrc] ********************************************************
changed: [vccw.dev]

TASK [Install Ruby gems] *******************************************************
changed: [vccw.dev] => (item=bundler)
changed: [vccw.dev] => (item=wordmove)

TASK [Place a ~/.npmrc] ********************************************************
changed: [vccw.dev]

TASK [Install npm packages] ****************************************************

TASK [Check the `phpcs` exists.] ***********************************************
changed: [vccw.dev]

TASK [Setup the WordPress coding standard] *************************************
skipping: [vccw.dev]

TASK [Checkout the WordPress i18n Tools] ***************************************
changed: [vccw.dev]

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [vccw.dev]

TASK [Allow remote connections to MySQL] ***************************************
changed: [vccw.dev]

TASK [Place ~/.my.cnf] *********************************************************
changed: [vccw.dev]

TASK [Create SSL dir] **********************************************************
changed: [vccw.dev]

TASK [Create SSL keys] *********************************************************
changed: [vccw.dev]

TASK [Replacing the Apache User] ***********************************************
changed: [vccw.dev]

TASK [Replacing the Apache Group] **********************************************
changed: [vccw.dev]

TASK [Place /etc/apache2/sites-available/site.conf] ****************************
changed: [vccw.dev]

TASK [Enable virtual host for WordPress] ***************************************
changed: [vccw.dev]

TASK [Update php.ini] **********************************************************
changed: [vccw.dev] => (item={'value': u'UTF-8', 'key': u'default_charset'})
changed: [vccw.dev] => (item={'value': False, 'key': u'short_open_tag'})
changed: [vccw.dev] => (item={'value': True, 'key': u'xdebug.remote_connect_back'})
changed: [vccw.dev] => (item={'value': u'VCCWDEBUG', 'key': u'xdebug.idekey'})
changed: [vccw.dev] => (item={'value': True, 'key': u'xdebug.remote_autostart'})
changed: [vccw.dev] => (item={'value': u'/usr/bin/env catchmail', 'key': u'sendmail_path'})
changed: [vccw.dev] => (item={'value': True, 'key': u'xdebug.profiler_enable'})
changed: [vccw.dev] => (item={'value': u'UTF-8', 'key': u'mbstring.internal_encoding'})
changed: [vccw.dev] => (item={'value': u'/tmp', 'key': u'session.save_path'})
changed: [vccw.dev] => (item={'value': u'1024M', 'key': u'upload_max_filesize'})
changed: [vccw.dev] => (item={'value': u'neutral', 'key': u'mbstring.language'})
changed: [vccw.dev] => (item={'value': u'127.0.0.1', 'key': u'xdebug.remote_host'})
changed: [vccw.dev] => (item={'value': u'UTC', 'key': u'date.timezone'})
changed: [vccw.dev] => (item={'value': True, 'key': u'xdebug.remote_enable'})
changed: [vccw.dev] => (item={'value': 9000, 'key': u'xdebug.remote_port'})
changed: [vccw.dev] => (item={'value': u'1024M', 'key': u'post_max_size'})

TASK [Install mailcatcher] *****************************************************
changed: [vccw.dev]

TASK [Add mailcatcher to service] **********************************************
changed: [vccw.dev]

TASK [Start mailcatcher] *******************************************************
fatal: [vccw.dev]: FAILED! => {"changed": false, "failed": true, "msg": "Error when trying to enable mailcatcher: rc=1 mailcatcher.service is not a native service, redirecting to systemd-sysv-install\nExecuting /lib/systemd/systemd-sysv-install enable mailcatcher\nupdate-rc.d: error: mailcatcher Default-Start contains no runlevels, aborting.\n"}

NO MORE HOSTS LEFT *************************************************************

RUNNING HANDLER [restart apache] ***********************************************

RUNNING HANDLER [restart mysql] ************************************************
        to retry, use: --limit @/vagrant/provision/playbook.retry

PLAY RECAP *********************************************************************
vccw.dev                   : ok=32   changed=29   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by dheerajbhaskar** [comment]
Deleted the root folder (vccw folder), updated vccw (cloned from branch), removed the Vms and re-provisioned it again. No errors. 

One thing I realized was my WordPress directory was empty when I had this error. And it wasn't getting resolved how many ever times I re-provisioned it. 

Perhaps, a network error (my Internet is very stable at 30 mbps up and down), even if there was an error it would've been momentary. 

Anyway, if this recurs, I shall provide more details, and help debug it. Especially, now that I know what to expect from a working installation. 

Feel free to close this issue or leave it open.

**Comment by miya0001** [comment]
Thanks @dheerajbhaskar.
Do you use the latest version of the VCCW?

I had the same problem, so I improved the script of the mailcatcher.

**Comment by dheerajbhaskar** [comment]
@miya0001 when I reported the issue, I was on v3.03. 

When I updated to v3.05, the issue was resolved. If you've identified and resolved this issue as you're implying, I shall go ahead and close the issue. Let me know if you want it otherwise. 

PS: Thanks a lot for your effort in maintaining this, this some really good work 👍

**Comment by miya0001** [comment]
Thanks!

> If you've identified and resolved this issue as you're implying, I shall go ahead and close the issue. Let me know if you want it otherwise.

Actually, I am not sure. 😄 
But I am hoping it will be solved.
