### ISSUE TITLE
Web connection to vccw 

### ISSUE THREAD

**Issue by acontini** [vccw-team/vccw#200]
Operating System: Ubuntu 16.04lts
Vagrant Version: n/a
Virtual Box Version: n/a

Hello, is it normal that once I installed vccw as per instruction and I connect on 192.168.33.10 through the web browser, the only page that appears is the Apache confirmation that the web server is up and running? Do I need to do something else to activate WordPress?
Thanks for your help.

**Comment by miya0001** [comment]
WordPress should be displayed.
