### ISSUE TITLE
Composer fail to install phpunit, and fail to start up properly

### ISSUE THREAD

**Issue by waviaei** [vccw-team/vccw#208]
Operating System: OSX 10.11.16
Vagrant Version: 1.9.1
Virtual Box Version: 5.1.14
vccw: 3.0.10

Creating new setup with `vccw up` finishes, but you cannot access the site. 
Looking back  up at the log, it seems to be failing where installing phpunit.

> TASK [Install Composer libraries] **********************************************
changed: [vccw.dev] => (item=hirak/prestissimo:*)
failed: [vccw.dev] (item=phpunit/phpunit:*) => {"failed": true, "item": "phpunit/phpunit:*", "msg": "You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug ./composer.json has been updated Loading composer repositories with package information Updating dependencies (including require-dev) - Installing symfony/yaml (v3.2.2) Loading from cache Installation failed, reverting ./composer.json to its original content. The following exception is caused by a lack of memory or swap, or not having swap configured Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details PHP Warning: proc_open(): fork failed - Cannot allocate memory in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php on line 957 PHP Stack trace: PHP 1. {main}() /usr/local/bin/composer:0 PHP 2. require() /usr/local/bin/composer:24 PHP 3. Composer\\Console\\Application->run() phar:///usr/local/bin/composer/bin/composer:43 PHP 4. Symfony\\Component\\Console\\Application->run() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:104 PHP 5. Symfony\\Component\\Console\\Application->renderException() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:130 PHP 6. Symfony\\Component\\Console\\Application->getTerminalWidth() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:651 PHP 7. Symfony\\Component\\Console\\Application->getTerminalDimensions() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:718 PHP 8. Symfony\\Component\\Console\\Application->getSttyColumns() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:757 PHP 9. proc_open() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:957 [ErrorException] proc_open(): fork failed - Cannot allocate memory require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...", "stdout": "You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug\n./composer.json has been updated\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\n  - Installing symfony/yaml (v3.2.2)\n    Loading from cache\n\nInstallation failed, reverting ./composer.json to its original content.\nThe following exception is caused by a lack of memory or swap, or not having swap configured\nCheck https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details\n\nPHP Warning:  proc_open(): fork failed - Cannot allocate memory in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php on line 957\nPHP Stack trace:\nPHP   1. {main}() /usr/local/bin/composer:0\nPHP   2. require() /usr/local/bin/composer:24\nPHP   3. Composer\\Console\\Application->run() phar:///usr/local/bin/composer/bin/composer:43\nPHP   4. Symfony\\Component\\Console\\Application->run() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:104\nPHP   5. Symfony\\Component\\Console\\Application->renderException() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:130\nPHP   6. Symfony\\Component\\Console\\Application->getTerminalWidth() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:651\nPHP   7. Symfony\\Component\\Console\\Application->getTerminalDimensions() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:718\nPHP   8. Symfony\\Component\\Console\\Application->getSttyColumns() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:757\nPHP   9. proc_open() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:957\n                                                     \n  [ErrorException]                                   \n  proc_open(): fork failed - Cannot allocate memory  \n                                                     \n\nrequire [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...\n\n", "stdout_lines": ["You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug", "./composer.json has been updated", "Loading composer repositories with package information", "Updating dependencies (including require-dev)", "  - Installing symfony/yaml (v3.2.2)", "    Loading from cache", "", "Installation failed, reverting ./composer.json to its original content.", "The following exception is caused by a lack of memory or swap, or not having swap configured", "Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details", "", "PHP Warning:  proc_open(): fork failed - Cannot allocate memory in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php on line 957", "PHP Stack trace:", "PHP   1. {main}() /usr/local/bin/composer:0", "PHP   2. require() /usr/local/bin/composer:24", "PHP   3. Composer\\Console\\Application->run() phar:///usr/local/bin/composer/bin/composer:43", "PHP   4. Symfony\\Component\\Console\\Application->run() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:104", "PHP   5. Symfony\\Component\\Console\\Application->renderException() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:130", "PHP   6. Symfony\\Component\\Console\\Application->getTerminalWidth() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:651", "PHP   7. Symfony\\Component\\Console\\Application->getTerminalDimensions() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:718", "PHP   8. Symfony\\Component\\Console\\Application->getSttyColumns() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:757", "PHP   9. proc_open() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:957", "                                                     ", "  [ErrorException]                                   ", "  proc_open(): fork failed - Cannot allocate memory  ", "                                                     ", "", "require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...", ""]}
changed: [vccw.dev] => (item=squizlabs/php_codesniffer:*)
...ignoring
changed: [vccw.dev] => (item=wp-coding-standards/wpcs:*)

**Comment by miya0001** [comment]
It is a problem of network or so.
You can see WordPress if we have a problem on getting composer.
If you want to use phpunit, please try vagrant provision.

**Comment by ClearMarble** [comment]
I'm having pretty much the exact same problem on Windows 10, Vagrant 1.9.1, VBox 5.1.14, vccw 3.0.10.

Tried destroying and creating from scratch several times. Anything one can do to prevent this error?

```
TASK [Install Composer libraries] **********************************************
changed: [vccw.dev] => (item=hirak/prestissimo:*)
failed: [vccw.dev] (item=phpunit/phpunit:*) => {"failed": true, "item": "phpunit/phpunit:*", "msg": "You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug ./composer.json has been updated Loading composer repositories with package information Updating dependencies (including require-dev) - Installing symfony/yaml (v3.2.2) Loading from cache Installation failed, reverting ./composer.json to its original content. The following exception is caused by a lack of memory or swap, or not having swap configured Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details PHP Warning: proc_open(): fork failed - Cannot allocate memory in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php on line 957 PHP Stack trace: PHP 1. {main}() /usr/local/bin/composer:0 PHP 2. require() /usr/local/bin/composer:24 PHP 3. Composer\\Console\\Application->run() phar:///usr/local/bin/composer/bin/composer:43 PHP 4. Symfony\\Component\\Console\\Application->run() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:104 PHP 5. Symfony\\Component\\Console\\Application->renderException() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:130 PHP 6. Symfony\\Component\\Console\\Application->getTerminalWidth() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:651 PHP 7. Symfony\\Component\\Console\\Application->getTerminalDimensions() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:718 PHP 8. Symfony\\Component\\Console\\Application->getSttyColumns() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:757 PHP 9. proc_open() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:957 [ErrorException] proc_open(): fork failed - Cannot allocate memory require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...", "stdout": "You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug\n./composer.json has been updated\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\n  - Installing symfony/yaml (v3.2.2)\n    Loading from cache\n\nInstallation failed, reverting ./composer.json to its original content.\nThe following exception is caused by a lack of memory or swap, or not having swap configured\nCheck https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details\n\nPHP Warning:  proc_open(): fork failed - Cannot allocate memory in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php on line 957\nPHP Stack trace:\nPHP   1. {main}() /usr/local/bin/composer:0\nPHP   2. require() /usr/local/bin/composer:24\nPHP   3. Composer\\Console\\Application->run() phar:///usr/local/bin/composer/bin/composer:43\nPHP   4. Symfony\\Component\\Console\\Application->run() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:104\nPHP   5. Symfony\\Component\\Console\\Application->renderException() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:130\nPHP   6. Symfony\\Component\\Console\\Application->getTerminalWidth() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:651\nPHP   7. Symfony\\Component\\Console\\Application->getTerminalDimensions() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:718\nPHP   8. Symfony\\Component\\Console\\Application->getSttyColumns() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:757\nPHP   9. proc_open() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:957\n                                                     \n  [ErrorException]                                   \n  proc_open(): fork failed - Cannot allocate memory  \n                                                     \n\nrequire [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...\n\n", "stdout_lines": ["You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug", "./composer.json has been updated", "Loading composer repositories with package information", "Updating dependencies (including require-dev)", "  - Installing symfony/yaml (v3.2.2)", "    Loading from cache", "", "Installation failed, reverting ./composer.json to its original content.", "The following exception is caused by a lack of memory or swap, or not having swap configured", "Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details", "", "PHP Warning:  proc_open(): fork failed - Cannot allocate memory in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php on line 957", "PHP Stack trace:", "PHP   1. {main}() /usr/local/bin/composer:0", "PHP   2. require() /usr/local/bin/composer:24", "PHP   3. Composer\\Console\\Application->run() phar:///usr/local/bin/composer/bin/composer:43", "PHP   4. Symfony\\Component\\Console\\Application->run() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:104", "PHP   5. Symfony\\Component\\Console\\Application->renderException() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:130", "PHP   6. Symfony\\Component\\Console\\Application->getTerminalWidth() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:651", "PHP   7. Symfony\\Component\\Console\\Application->getTerminalDimensions() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:718", "PHP   8. Symfony\\Component\\Console\\Application->getSttyColumns() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:757", "PHP   9. proc_open() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:957", "                                                     ", "  [ErrorException]                                   ", "
proc_open(): fork failed - Cannot allocate memory  ", "                                                     ", "", "require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...", ""]}
changed: [vccw.dev] => (item=squizlabs/php_codesniffer:*)
...ignoring
changed: [vccw.dev] => (item=wp-coding-standards/wpcs:*)
```

**Comment by miya0001** [comment]
I know we sometimes have the same problem on installing composer but I am not sure the reason.

If you don't need phpunit or you already install phpunit in your host machine.
You can put following line into your `site.yml`.

```
composers: []
```

It will skip installing composer libraries and provisioning will be faster. :)

**Comment by waviaei** [comment]
OK. Sorry. I made an error on site.yml. I think this was not effecting this error.

(I thought I had edited hostname on site.yml, but I had not. So I was trying to access tujtheme.dev where VCCW actually created vccw.dev ... (>_<))

I tried the clean vccw once again. It gives same error, but the site will run all as normal. It just tells me this when I try to run phpunit

> The program 'phpunit' is currently not installed. You can install it by typing:
sudo apt install phpunit

@ClearMarble So, if you don't need phpunit, you can probably ignore that error, or do as @miya0001 mentioned, and skip it.
