### ISSUE TITLE
Want to change the php version from 7.0.8 to 5.6.9

### ISSUE THREAD

**Issue by byron222** [vccw-team/vccw#211]
Operating System:Windows 10
Vagrant Version: 1.9.1
Virtual Box Version: 5.1.14

**Comment by miya0001** [comment]
We aren`t thinking about installing multiple version of PHP, because we need a lot of effort to realize that.

**Comment by josuevalrob** [comment]
Any solution to this? I want to run php 5.6

**Comment by miya0001** [comment]
@josuevalrob 

I wrote a shell script to do that. Please try!
https://github.com/vccw-team/change-php-version
