### ISSUE TITLE
Warning: mysqli_real_connect(): (HY000/2002)

### ISSUE THREAD

**Issue by glrodasz** [vccw-team/vccw#220]
Operating System: macOS Sierra 10.12.3
Vagrant Version: 1.8.6
Virtual Box Version: 5.1.6

I'm having the following every time after a few minutes of just play with the wordpress site.

`Warning: mysqli_real_connect(): (HY000/2002): No such file or directory in /var/www/html/wp-includes/wp-db.php on line 1538`

![image](https://cloud.githubusercontent.com/assets/1431663/22858886/3c2d8a68-f098-11e6-90fe-381f9d7bf66d.png)

**Comment by miya0001** [comment]
Please try `vagrant provision && vagrant reload`.

**Comment by glrodasz** [comment]
@miya0001 Your solution works for a few days but it is happening again. How can I help to catch the bug?
