### ISSUE TITLE
Fresh install, assets not found

### ISSUE THREAD

**Issue by netm** [vccw-team/vccw#222]
Operating System: Ubuntu
Vagrant Version: 1.91
Virtual Box Version: 5

Just installed vccw for the first time, all good getting it working but asset links not loading on the site once i go to the VM ip address. See attached...

![image](https://cloud.githubusercontent.com/assets/1432243/22870878/903a49b0-f210-11e6-8541-c9dca8608e50.png)

**Comment by miya0001** [comment]
You should add `192.168.33.10 vccw.dev` into `/etc/hosts`, then acccess http://vccw.dev/.
Or use vagrant-hostsupdater.

**Comment by miya0001** [comment]
https://github.com/cogitatio/vagrant-hostsupdater
