### ISSUE TITLE
Unknown collation: 'utf8mb4_unicode_520_ci' (Wordmove::ShellCommandError)

### ISSUE THREAD

**Issue by mrky007** [vccw-team/vccw#229]
Operating System: Ubuntu 16.04.
Vagrant Version: Vagrant 1.9.1
Virtual Box Version: 5.1.14 r112924 (Qt5.5.1)

I've setup my development environment and everything works great, but when I try to push all to production server I always get: Unknown collation: 'utf8mb4_unicode_520_ci' (Wordmove::ShellCommandError) for Database Pushig.

I've read somwhere that this might be a problem with mysql version, development server uses: 5.7.16 and live server has 5.5.54 installed.

Has anyone encountered / fixed this issue?

**Comment by mrky007** [comment]
In case anyone else out there has this problem, the solution by @pioneerskies can be found [here](https://dev.welaika.com/blog/2016/10/12/wordpress-db-fix.html)

**Comment by miya0001** [comment]
Oh, this solution looks nice. 👍
