### ISSUE TITLE
Activating local plugins

### ISSUE THREAD

**Issue by chrispage1** [vccw-team/vccw#230]
Hi,

It would be nice if my defined plugins list checked locally first to see if that plugin already existed in the folder structure before throwing a recipe error.

For example my plugins list - 

plugins:
 - dynamic-hostsupdater
 - advanced-custom-fields-pro

Now advanced-custom-fields-pro already exists in my local file structure but the recipe breaks because it can't find ACF Pro on the WordPress store.

Is this possible?

Chris.

**Comment by miya0001** [comment]
VCCW always attempt to download latest plugins which defined in your `site.yml`.
If you don't want it to do that, please remove the plugin from `site.yml` and place the `provision-post.sh` like following.

```
#!/usr/bin/env bash

set -ex

sudo -u vagrant -- wp plugin activate advanced-custom-fields-pro
```

It will be executed at the end of the provision, so `advanced-custom-fields-pro` will be activated automatically.

**Comment by chrispage1** [comment]
@miya0001 thank you very much for your feedback. so am i right in saying that provision-post.sh gets executed automatically when spinning an instance? I might just use this to import a DB too!

**Comment by miya0001** [comment]
> so am i right in saying that provision-post.sh gets executed automatically when spinning an instance? I might just use this to import a DB too!

Yup 😄
