### ISSUE TITLE
Windows Apache Installed but WP

### ISSUE THREAD

**Issue by tinsterman** [vccw-team/vccw#234]
Operating System: Windows 10
Vagrant Version: 1.9.2
Virtual Box Version: 5.1.8

On Linux was able to run the software no problem at all. However, trying to do the same for a team member running windows and when reaching http://192.168.33.10/ only see Apache default screen. 

Any ideas?

**Comment by miya0001** [comment]
Let them try `vagrant provision`.
If they have problems then, please give us output.

**Comment by grintender** [comment]
Im having same issue. Can remove vagrant machine, and then up it again so it reinstalls wordpress folder


$ vagrant destroy && vagrant up --provision
    vccw.dev: Are you sure you want to destroy the 'vccw.dev' VM? [y/N] y
==> vccw.dev: Destroying VM and associated drives...
Bringing machine 'vccw.dev' up with 'virtualbox' provider...
==> vccw.dev: Importing base box 'vccw-team/xenial64'...
==> vccw.dev: Matching MAC address for NAT networking...
==> vccw.dev: Checking if box 'vccw-team/xenial64' is up to date...
A VirtualBox machine with the name 'vccw.dev' already exists.
Please use another name or delete the machine with the existing
name, and try again.


$ vagrant status
Current machine states:

vccw.dev                  poweroff (virtualbox)

The VM is powered off. To restart the VM, simply run `vagrant up`


$ vagrant up
Bringing machine 'vccw.dev' up with 'virtualbox' provider...
==> vccw.dev: Checking if box 'vccw-team/xenial64' is up to date...
A VirtualBox machine with the name 'vccw.dev' already exists.
Please use another name or delete the machine with the existing
name, and try again.

**Comment by tinsterman** [comment]
I think the error was in the hosts file for windows. I have now edited that and it seems to be working.
If you need to know how to edit the host file follow https://www.petri.com/easily-edit-hosts-file-windows-10
