### ISSUE TITLE
Machine is already provisioned

### ISSUE THREAD

**Issue by apidevlab** [vccw-team/vccw#239]
Operating System: Win 7 x64
Vagrant Version: 1.91
Virtual Box Version: VirtualBox-5.1.18-114002-Win

I have no problem initialising and running the `vagrant up` command and vccw works as expected so far. The issue I have is that after performing a `vagrant halt` (switch machine off) and then running `vagrant up` (switch back on) I get a **Machine is already provisioned** issue. 

```
==> vccw.dev: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> vccw.dev: flag to force provisioning. Provisioners marked to run always will still run.
```

The output suggests using the `-no-provisioning` flag but then the machine simply halts obviously this behaviour is not ideal as each switch off kills the box.

**Comment by miya0001** [comment]
I do not think it is a problem of the VCCW.
Are there same problem with VVV or another vagrant machine?
