### ISSUE TITLE
Mutiple VCCW Wordpress projects on Ubuntu

### ISSUE THREAD

**Issue by notatamas** [vccw-team/vccw#241]
Operating System: Ubuntu 16.04
Vagrant Version: 1.9.3
Virtual Box Version: 5.1.18

I have one VCCW which works just fine. But I have to start a new wordpress project and I read [here](https://github.com/vccw-team/vccw/issues/101) that I just have to unzip the VCCW, change the hostname and ip, and it should be good to go.

However, when I SSH into my virtualbox/vagrant, I see that my original VCCW project is just simply in the /var/www/html folder. 

So if I just do a "vagrant up" in a new VCCW project with a changed hostname and ip, aren't the two projects colliding in some way? Since both of them are simply installed to the /var/www/html folder. In XAMPP I would need to put these in some subfolders.

Thanks in advance.

**Comment by marushu** [comment]
How about creating another directory, downloading / unzipping VCCW into it, editing site.yml, and vagrant up?
You can start several at the same time.

**Comment by miya0001** [comment]
If you've installed WP-CLI in your host machine.
Please try following.
https://github.com/vccw-team/scaffold-vccw

**Comment by notatamas** [comment]
Thanks, it was easier than I thought.
