### ISSUE TITLE
Sharing the VCCW database on Dropbox

### ISSUE THREAD

**Issue by notatamas** [vccw-team/vccw#242]
Operating System: Ubuntu 16.04
Vagrant Version: 1.9.3
Virtual Box Version: 5.1.18

I store my VCCW vagrant folder on Dropbox. What if I would like to open the same project from a different computer using Dropbox?
Let's say I would have installed the same requirements on the other computer. 
Can I share the DB folder the same way as the 'wordpress' folder so I would just do a vagrant up?
Is something like this even possible?

Thanks in advance.

**Comment by miya0001** [comment]
You can share VCCW folder with git or so.
But real time sharing is not supported.
