### ISSUE TITLE
WordMove Requires Ruby 2.4

### ISSUE THREAD

**Issue by jhjm32087** [vccw-team/vccw#248]
During a fresh install of VCCW on my local box word move is missing.

`failed: [vccw.dev] (item=wordmove) => {"cmd": "/usr/bin/gem install --version 2.0.2 --user-install --no-document wordmove", "failed": true, "item": "wordmove", "msg": "WARNING:  You don't have /home/vagrant/.gem/ruby/2.3.0/bin in your PATH,\n\t  gem executables will not run.\nERROR:  Error installing wordmove:\n\tphotocopier requires Ruby version ~> 2.4.", "rc": 1, "stderr": "WARNING:  You don't have /home/vagrant/.gem/ruby/2.3.0/bin in your PATH,\n\t  gem executables will not run.\nERROR:  Error installing wordmove:\n\tphotocopier requires Ruby version ~> 2.4.\n", "stdout": "Successfully installed colorize-0.8.1\nSuccessfully installed thor-0.19.4\nSuccessfully installed i18n-0.8.1\nSuccessfully installed thread_safe-0.3.6\nSuccessfully installed tzinfo-1.2.3\nSuccessfully installed concurrent-ruby-1.0.5\nSuccessfully installed activesupport-5.1.1\nSuccessfully installed net-ssh-4.1.0\nSuccessfully installed net-scp-1.2.1\nSuccessfully installed net-ssh-gateway-2.0.0\n", "stdout_lines": ["Successfully installed colorize-0.8.1", "Successfully installed thor-0.19.4", "Successfully installed i18n-0.8.1", "Successfully installed thread_safe-0.3.6", "Successfully installed tzinfo-1.2.3", "Successfully installed concurrent-ruby-1.0.5", "Successfully installed activesupport-5.1.1", "Successfully installed net-ssh-4.1.0", "Successfully installed net-scp-1.2.1", "Successfully installed net-ssh-gateway-2.0.0"]}`

Operating System:
Windows 10

Vagrant Version:
1.9.5

Virtual Box Version:
5.1.22

**Comment by jhjm32087** [comment]
As a side fix you can manually install an older version on ruby 2.3 to get this to work by the following command:
`gem install wordmove -v 2.0.0`

**Comment by miya0001** [comment]
Oh! Thanks!

**Comment by jhjm32087** [comment]
@miya0001, I did a successful install but the wordmove command is not being installed globally.

**Comment by torounit** [comment]
@jhjm32087 Please try vccw 2.3.0.

it will be like this.

```bash
$ which wordmove
/home/vagrant/.gem/ruby/2.3.0/bin/wordmove
```
