### ISSUE TITLE
Changing hostname in default.yml causes new box to be provisioned

### ISSUE THREAD

**Issue by itslittlejohn** [vccw-team/vccw#265]
Operating System: Windows 10
Vagrant Version: 1.9.7
Virtual Box Version: 5.1.26r117224

After initial `vagrant up`, I want to change the hostname from vccw.dev to something custom. Doing `vagrant halt` and `vagrant up` causes a brand new box to be provisioned after I change the `hostname` property in default.yml.

If this is not the correct way to change the hostname for an existing vagrant box using this configuration, can someone point me in the right direction?

**Comment by miya0001** [comment]
Unfortunately , you have to destroy your machine by `vagrant destroy`.
