### ISSUE TITLE
Should we change the default domain ?

### ISSUE THREAD

**Issue by hideokamoto** [vccw-team/vccw#275]
Chrome to force .dev domains to HTTPS via preloaded HSTS.
https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

So, http://vccw.dev maybe force redirect to https://vccw.dev.
I think we should change the default domain like http: //vccw.local.

What do you think about this news?

Thanks.

**Comment by miya0001** [comment]
Thanks for information. :)

**Comment by hideokamoto** [comment]
https://github.com/vccw-team/vccw/pull/277
