### ISSUE TITLE
'Getting started' says incorrect URL

### ISSUE THREAD

**Issue by pquerner** [vccw-team/vccw#278]
Operating System: Windows 10 x64
Vagrant Version: 2.0.0
Virtual Box Version: 5.1.28

'Getting Started' [1] says URL is  http://vccw.test/, when the installation from 'vagrant up' added the following to the ```hosts``` file:

```
192.168.33.10  vccw.dev  # VAGRANT: xxxxxxx (vccw.dev) / xx
```

[1] http://vccw.cc/#h2-2

**Comment by miya0001** [comment]
Ah, thanks. :)

I forgot I have to ship new version.
The default url will be changed at next release.
