### ISSUE TITLE
Separate wordpress directories and installs on same instance of VCCW

### ISSUE THREAD

**Issue by ACWalker** [vccw-team/vccw#281]
Operating System: Windows 10
Vagrant Version: 2.0.0
Virtual Box Version: 5.1.28 r117968

Hello,

I am wondering how one can install separate installations of wordpress into subdirectories, while still using the same VCCW installation.

For example two installations in:
/wordpress/site1
/wordpress/site2

Thanks

**Comment by miya0001** [comment]
Do you mean virtualhost?
VCCW doesn't support virtualhost.

**Comment by ACWalker** [comment]
I'm not entirely sure it's virtualhost, but I have seen in previous issues that people have got the functionality I described. I was wondering how/if it was possible to do

**Comment by miya0001** [comment]
If you need one more VCCW environments.

* Download VCCW.
* Update the `hostname` and `ip` in the `site.yml`.
* Then `vagrant up`

http://vccw.cc/#h2-4

Thanks 😊

**Comment by ACWalker** [comment]
Ok thanks, will try that!
