### ISSUE TITLE
[Question] What forces you to keep Ruby at 2.3?

### ISSUE THREAD

**Issue by pioneerskies** [vccw-team/vccw#300]
Hi guys,

I'm from the Wordmove maintainers team. As far as I can see, you are using Wordmove v2.0.0 because you have Ruby 2.3.0 inside the vagrant VM. Is that right? I cannot understand where the ruby version in configured so I cannot guess why it is not upgrade-able.

I think it's a pity, because we've implemented new features and bugfixes since Wordmove 2.0.0. Let me know if I could help you someway.

And feel free to close my issue at your will ;)

Cheers

**Comment by pioneerskies** [comment]
In the meantime Wordmove 2.4 is out and has another new big feature; I'm feeling pain knowing that vccw user can't benefit from all that work :) 🤙

**Comment by miya0001** [comment]
Hi @pioneerskies 

Thanks for suggestion. :)
VCCW is installing the ruby in this box.
https://github.com/vccw-team/vccw-xenial64

We will update it as soon as possible.
Thanks again. 😊

**Comment by pioneerskies** [comment]
Sounds good :)

Always feel free to contact me if having any issue, question, need with Wordmove.

Closing this one since my question was answered.

Thank you very much.

**Comment by miya0001** [comment]
Hi @pioneerskies 

We updated ruby to 2.4. Thanks! 😊
