### ISSUE TITLE
Database reset every 15-30 minutes

### ISSUE THREAD

**Issue by lukasniestrat** [vccw-team/vccw#305]
Operating System: macOS
Vagrant Version: 2.0.1
Virtual Box Version: 5.2.4

The database reset every 15-30 minutes, I don't know why, but it's very annoying.
First you have to login into WordPress again, after that the database rest itself.

please please fix it!

**Comment by miya0001** [comment]
Hi @lukasniestrat 

We don't have the problem. How can we reproduce it?

**Comment by lukasniestrat** [comment]
I have totally no idea. I think, I will destroy the box and make a new setup. Maybe it's a local bug on my machine.

**Comment by jameswagoner** [comment]
I have rebuilt the box 3 times now. I am experiencing the same reset. Like there is some backup that gets restored.
