### ISSUE TITLE
404-error downloading 'vccw-team/xenial64'-box from atlas-hashicorps

### ISSUE THREAD

**Issue by thaeny-dev** [vccw-team/vccw#312]
Operating System: Ubuntu 16.04
Vagrant Version: 1.9.1
Virtual Box Version: 5.14.1

I unpacked a fresh downloaded vccw-3.16.1.zip today and during the 'vagrant up' when he should download a new 'vccw-team/xenial64'-box I will get an 404-error:

> The box 'vccw-team/xenial64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

>URL: ["https://atlas.hashicorp.com/vccw-team/xenial64"]
Error: The requested URL returned error: 404 Not Found

When I enter the URL into the Browser I will get the an 404-error as well:
https://atlas.hashicorp.com/vccw-team/xenial64

It would be great when this could be fixed.

**Comment by kalpaitch** [comment]
++

**Comment by kalpaitch** [comment]
https://github.com/hashicorp/vagrant/issues/9442#issuecomment-363080565

**Comment by thaeny-dev** [comment]
I updated vagrant to 1.9.8 and then the problem was fixed.
(don't forget to update the metadata_url in already existing boxes)
