### ISSUE TITLE
What Do I Do With Step 5 Zip?

### ISSUE THREAD

**Issue by davidshq** [vccw-team/vccw#326]
Hi Folks,

Minor item, but the directions (Step 5) on vccw.cc suggest downloading the 
vccw-x.xx.x.zip file but then don't provide any instructions on what to do with the zip.

Step 6 says to create a folder (which is naming vccw-x.xx.x, so I'm assuming that it is meant to extract the zip into this folder) but never again mentions the zip.

**Comment by miya0001** [comment]
Sorry for poor documentation. 😊 

5. Download `.zip`.
6. Unzip the `vccw-x.xx.x.zip`.
7. Change into the directory with the terminal.
8. `vagrant up`

We are hoping to improve our documentation.
If you have a moment, please send pull-request. We always welcome it.

Thanks! 😊

**Comment by miya0001** [comment]
Ah, the repository of the documentation is following.
https://github.com/vccw-team/vccw.cc
