### ISSUE TITLE
How do I import an existing wordpress database in vccw/vagrant?

### ISSUE THREAD

**Issue by codeliger** [vccw-team/vccw#329]
Operating System: Ubuntu 16.04
Vagrant Version: 2.1.1
Virtual Box Version: 5.1.3.4

**Comment by miya0001** [comment]
Try `wp db import`.

**Comment by dragon788** [comment]
If you want the database and all the site content, try All-in-One WP Migration (up to 500MB backups are free). 

### Make a backup of the source site
* Install All-In-One WP Migration from the plugins page
* Export a "File" backup and put it somewhere safe (local for dev and Google Drive?)

### Restore to vccw site
* start up your VM with `vagrant up`
* Install All-In-One WP Migration from the plugins page
* Import the backup (WILL WIPE EVERYTHING IN LOCAL SITE).

**Comment by eduardocgarza** [comment]
@miya0001 

> Try `wp db import`.

Could you elaborate on this? How can I set up an existing website on vccw? New sites are easy but there's no info on the documentation about existing sites.

**Comment by tkc49** [comment]
@eduardocgarza 
Does your site allow for an SSH connection?
If your site allow for an SSH connection, you can WordMove on VCCW.
