### ISSUE TITLE
phpunit: No tests executed!

### ISSUE THREAD

**Issue by tkc49** [vccw-team/vccw#331]
Operating System: Mac OS Serria
Vagrant Version: 3.18.0
Virtual Box Version: 5.2.8

Please help me😵
the following message is output When phpunit is executed.
`No tests executed!`

log
> vagrant@vccw:/vagrant/wordpress/wp-content/plugins/test$ phpunit
> Installing...
> Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
> Not running ajax tests. To execute these, use --group ajax.
> Not running ms-files tests. To execute these, use --group ms-files.
> Not running external-http tests. To execute these, use --group external-http.
> PHPUnit 5.6.0 by Sebastian Bergmann and contributors.
> 
> 
> 
> Time: 1.25 seconds, Memory: 26.00MB
> 
> No tests executed!

But It works if I specify the path to the test file.

log
> vagrant@vccw:/vagrant/wordpress/wp-content/plugins/test$ phpunit tests/test-sample.php
> Installing...
> Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
> Not running ajax tests. To execute these, use --group ajax.
> Not running ms-files tests. To execute these, use --group ms-files.
> Not running external-http tests. To execute these, use --group external-http.
> PHPUnit 5.6.0 by Sebastian Bergmann and contributors.
> 
> .                                                                   1 / 1 (100%)
> 
> Time: 1.59 seconds, Memory: 28.00MB
> 
> OK (1 test, 1 assertion)

**Comment by miya0001** [comment]
Sorry for delaying. 😓 
Does your plugin have `phpunit.xml.dist`?

**Comment by tkc49** [comment]
@miya0001 
Thank you for your reply.
I fixed this issue.

"test-sample.php" excluded by default setting🙏
