### ISSUE TITLE
Chef never successfully completed!

### ISSUE THREAD

**Issue by vishvajit79** [vccw-team/vccw#334]
Operating System:ubuntu12.04
Vagrant Version:2
Virtual Box Version:

==> default: Running provisioner: chef_solo...
==> default: Detected Chef (latest) is already installed
==> default: Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: [2018-08-28T14:38:09+00:00] INFO: Started chef-zero at chefzero://localhost:1 with repository at /tmp/vagrant-chef/a7dd15ffd52b313f68f55251ed234ecc
==> default:   One version per cookbook
==> default: [2018-08-28T14:38:09+00:00] INFO: Forking chef instance to converge...
==> default: Starting Chef Client, version 13.4.24
==> default: [2018-08-28T14:38:09+00:00] INFO: *** Chef 13.4.24 ***
==> default: [2018-08-28T14:38:09+00:00] INFO: Platform: x86_64-linux
==> default: [2018-08-28T14:38:09+00:00] INFO: Chef-client pid: 2084
==> default: [2018-08-28T14:38:09+00:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
==> default: [2018-08-28T14:38:12+00:00] INFO: Setting the run_list to ["recipe[rabbitmongo]"] from CLI options
==> default: [2018-08-28T14:38:12+00:00] INFO: Run List is [recipe[rabbitmongo]]
==> default: [2018-08-28T14:38:12+00:00] INFO: Run List expands to [rabbitmongo]
==> default: [2018-08-28T14:38:12+00:00] INFO: Starting Chef Run for vagrant-340c28a7
==> default: [2018-08-28T14:38:12+00:00] INFO: Running start handlers
==> default: [2018-08-28T14:38:12+00:00] INFO: Start handlers complete.
==> default: resolving cookbooks for run list: ["rabbitmongo"]
==> default: [2018-08-28T14:38:12+00:00] INFO: Loading cookbooks [rabbitmongo@0.0.0]
==> default: Synchronizing Cookbooks:
==> default:   
==> default: - rabbitmongo (0.0.0)
==> default: Installing Cookbook Gems:
==> default: Compiling Cookbooks...
==> default: Converging 23 resources
==> default: Recipe: rabbitmongo::default
==> default:   
==> default: * apt_package[build-essential] action install
==> default:  (up to date)
==> default: 
==> default:   * apt_package[binutils-doc] action install
==> default:  (up to date)
==> default:   
==> default: * apt_package[autoconf] action install
==> default:  (up to date)
==> default:   
==> default: * apt_package[flex] action install
==> default:  (up to date)
==> default:   
==> default: * apt_package[bison] action install
==> default:  (up to date)
==> default:   * execute[apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10] action run
==> default: 
==> default:     [execute] Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.QiIQbwVpUd --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver keyserver.ubuntu.com --recv 7F0CEB10
==> default:               gpg: requesting key 7F0CEB10 from hkp server keyserver.ubuntu.com
==> default:               gpg: 
==> default: key 7F0CEB10: "Totally Legit Signing Key <mallory@example.org>" not changed
==> default:               gpg: key 7F0CEB10: "Richard Kreuter <richard@10gen.com>" not changed
==> default:               gpg: Total number processed: 2
==> default:               gpg:              unchanged: 2
==> default: [2018-08-28T14:38:12+00:00] INFO: execute[apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10] ran successfully
==> default:     - execute apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
==> default:   * execute[echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' >> /etc/apt/sources.list] action run
==> default: [2018-08-28T14:38:12+00:00] INFO: execute[Guard resource] ran successfully
==> default:  (skipped due to not_if)
==> default:   * execute[wget http://www.rabbitmq.com/rabbitmq-signing-key-public.asc] action run
==> default:     [execute] 
==> default: --2018-08-28 14:38:12--  http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
==> default:               
==> default: Resolving www.rabbitmq.com (www.rabbitmq.com)... 
==> default: 104.20.62.197, 104.20.63.197
==> default:               
==> default: Connecting to www.rabbitmq.com (www.rabbitmq.com)|104.20.62.197|:80... 
==> default: connected.
==> default:               
==> default: HTTP request sent, awaiting response... 
==> default: 200 OK
==> default:               
==> default: Length: unspecified [text/plain]
==> default:               
==> default: Saving to: `rabbitmq-signing-key-public.asc.3'
==> default:               
==> default:               
==> default:      0K .                                                      73.4M=0s
==> default:               
==> default:               
==> default: 2018-08-28 14:38:13 (73.4 MB/s) - `rabbitmq-signing-key-public.asc.3' saved [1702]
==> default:               
==> default: [2018-08-28T14:38:13+00:00] INFO: execute[wget http://www.rabbitmq.com/rabbitmq-signing-key-public.asc] ran successfully
==> default:     
==> default: - execute wget http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
==> default: 
==> default: 
==> default:   
==> default: * execute[apt-key add rabbitmq-signing-key-public.asc] action run
==> default: 
==> default:     [execute] OK
==> default: [2018-08-28T14:38:13+00:00] INFO: execute[apt-key add rabbitmq-signing-key-public.asc] ran successfully
==> default:     - execute apt-key add rabbitmq-signing-key-public.asc
==> default:   * execute[echo 'deb http://www.rabbitmq.com/debian/ testing main' >> /etc/apt/sources.list] action run
==> default: [2018-08-28T14:38:13+00:00] INFO: execute[Guard resource] ran successfully
==> default:  (skipped due to not_if)
==> default:   
==> default: * execute[wget http://dotdeb.org/dotdeb.gpg] action run
==> default:     [execute] 
==> default: --2018-08-28 14:38:13--  http://dotdeb.org/dotdeb.gpg
==> default:               
==> default: Resolving dotdeb.org (dotdeb.org)... 
==> default: 195.154.242.153
==> default:               Connecting to dotdeb.org (dotdeb.org)|195.154.242.153|:80... 
==> default: connected.
==> default:               
==> default: HTTP request sent, awaiting response... 
==> default: 301 Moved Permanently
==> default:               
==> default: Location: http://www.dotdeb.org/dotdeb.gpg [following]
==> default:               
==> default: --2018-08-28 14:38:13--  http://www.dotdeb.org/dotdeb.gpg
==> default:               
==> default: Resolving www.dotdeb.org (www.dotdeb.org)... 
==> default: 195.154.242.153
==> default:               
==> default: Reusing existing connection to dotdeb.org:80.
==> default:               
==> default: HTTP request sent, awaiting response... 
==> default: 200 OK
==> default:               
==> default: Length: 5299 (5.2K) [application/octet-stream]
==> default:               
==> default: Saving to: `dotdeb.gpg.3'
==> default:               
==> default:               
==> default:      0K .....                                                 100%  111M=0s
==> default:               
==> default:               
==> default: 2018-08-28 14:38:13 (111 MB/s) - `dotdeb.gpg.3' saved [5299/5299]
==> default:               
==> default: [2018-08-28T14:38:13+00:00] INFO: execute[wget http://dotdeb.org/dotdeb.gpg] ran successfully
==> default:     
==> default: - execute wget http://dotdeb.org/dotdeb.gpg
==> default: 
==> default: 
==> default:   
==> default: * execute[cat dotdeb.gpg | apt-key add -] action run
==> default: 
==> default:     [execute] OK
==> default: [2018-08-28T14:38:13+00:00] INFO: execute[cat dotdeb.gpg | apt-key add -] ran successfully
==> default:     - execute cat dotdeb.gpg | apt-key add -
==> default:   * execute[echo 'deb http://packages.dotdeb.org squeeze all' >> /etc/apt/sources.list] action run
==> default: [2018-08-28T14:38:13+00:00] INFO: execute[Guard resource] ran successfully
==> default:  (skipped due to not_if)
==> default:   * execute[echo 'deb-src http://packages.dotdeb.org squeeze all' >> /etc/apt/sources.list] action run
==> default: [2018-08-28T14:38:13+00:00] INFO: execute[Guard resource] ran successfully
==> default:  (skipped due to not_if)
==> default:   
==> default: * execute[apt-get update] action run
==> default:  (up to date)
==> default:   
==> default: * apt_package[mongodb-10gen] action install
==> default:  (up to date)
==> default:   
==> default: * apt_package[erlang] action install
==> default:  (up to date)
==> default:   
==> default: * apt_package[rabbitmq-server] action install
==> default:     
==> default: 
==> default:     
==> default: ================================================================================
==> default: 
==> default:     Error executing action `install` on resource 'apt_package[rabbitmq-server]'
==> default:     ================================================================================
==> default:     
==> default:     Mixlib::ShellOut::ShellCommandFailed
==> default:     ------------------------------------
==> default:     Expected process to exit with [0], but received '100'
==> default:     ---- Begin output of ["apt-get", "-q", "-y", "install", "rabbitmq-server=3.6.15-1"] ----
==> default:     STDOUT: Reading package lists...
==> default:     Building dependency tree...
==> default:     Reading state information...
==> default:     Some packages could not be installed. This may mean that you have
==> default:     requested an impossible situation or if you are using the unstable
==> default:     distribution that some required packages have not yet been created
==> default:     or been moved out of Incoming.
==> default:     The following information may help to resolve the situation:
==> default:     
==> default:     The following packages have unmet dependencies:
==> default:      rabbitmq-server : Depends: init-system-helpers (>= 1.13~) but it is not installable
==> default:                        Depends: erlang-nox (>= 1:16.b.3) but it is not going to be installed or
==> default:                                 esl-erlang (>= 1:16.b.3) but it is not installable
==> default:     STDERR: E: Unable to correct problems, you have held broken packages.
==> default:     ---- End output of ["apt-get", "-q", "-y", "install", "rabbitmq-server=3.6.15-1"] ----
==> default:     Ran ["apt-get", "-q", "-y", "install", "rabbitmq-server=3.6.15-1"] returned 100
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/rabbitmongo/recipes/default.rb
==> default:     
==> default:      57: package "rabbitmq-server"
==> default:      58: # Enable the rabbitmq management (web-based console) plugin
==> default:     
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/rabbitmongo/recipes/default.rb:57:in `from_file'
==> default:     
==> default:     apt_package("rabbitmq-server") do
==> default:       package_name "rabbitmq-server"
==> default:       action [:install]
==> default:       default_guard_interpreter :default
==> default:       declared_type :package
==> default:       cookbook_name "rabbitmongo"
==> default:       recipe_name "default"
==> default:     end
==> default:     
==> default:     System Info:
==> default:     ------------
==> default:     chef_version=13.4.24
==> default:     platform=ubuntu
==> default:     platform_version=12.04
==> default:     ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
==> default:     program_name=chef-solo worker: ppid=2079;start=14:38:09;
==> default:     executable=/opt/chef/bin/chef-solo
==> default:     
==> default: [2018-08-28T14:38:15+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: 
==> default: Running handlers:
==> default: [2018-08-28T14:38:15+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: 
==> default: [2018-08-28T14:38:15+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 5 resources updated in 05 seconds
==> default: [2018-08-28T14:38:15+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2018-08-28T14:38:15+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2018-08-28T14:38:15+00:00] ERROR: apt_package[rabbitmq-server] (rabbitmongo::default line 57) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
==> default: ---- Begin output of ["apt-get", "-q", "-y", "install", "rabbitmq-server=3.6.15-1"] ----
==> default: STDOUT: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: Some packages could not be installed. This may mean that you have
==> default: requested an impossible situation or if you are using the unstable
==> default: distribution that some required packages have not yet been created
==> default: or been moved out of Incoming.
==> default: The following information may help to resolve the situation:
==> default: 
==> default: The following packages have unmet dependencies:
==> default:  rabbitmq-server : Depends: init-system-helpers (>= 1.13~) but it is not installable
==> default:                    Depends: erlang-nox (>= 1:16.b.3) but it is not going to be installed or
==> default:                             esl-erlang (>= 1:16.b.3) but it is not installable
==> default: STDERR: E: Unable to correct problems, you have held broken packages.
==> default: ---- End output of ["apt-get", "-q", "-y", "install", "rabbitmq-server=3.6.15-1"] ----
==> default: Ran ["apt-get", "-q", "-y", "install", "rabbitmq-server=3.6.15-1"] returned 100
==> default: [2018-08-28T14:38:15+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by miya0001** [comment]
Sorry please use latest version of VCCW.
Thanks!
