### ISSUE TITLE
Can't load images or any file from http://vccw.test  I have to Type http://192.168.33.10/ in the browser to load the page

### ISSUE THREAD

**Issue by JinZhenlin** [vccw-team/vccw#336]
Operating System: OS X
Vagrant Version: 2.2.0
Virtual Box Version: 5.2
![screen shot 2018-11-04 at 12 46 14 pm](https://user-images.githubusercontent.com/25071806/47968451-df587080-e02f-11e8-9405-ea7cc201383f.png)

I previously used vccw like a year ago and since deleted everything (including vagrant and virtualbox). This time the browser has been failing to load everything from vccw.test upon the fresh install.

When I type _vagrant provision_ as suggested, it returns the following:
==> vccw.test: Running provisioner: ansible_local...
    vccw.test: Running ansible-playbook...

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [vccw.test]

TASK [Place a ~/.bash_profile] *************************************************
ok: [vccw.test]

TASK [Place a ~/.bash.d/] ******************************************************
ok: [vccw.test]

TASK [Place a ~/.bash.d/vccw.sh] ***********************************************
ok: [vccw.test]

TASK [Download the Composer] ***************************************************
ok: [vccw.test]

TASK [Run the Composer installer] **********************************************
changed: [vccw.test]

TASK [Create a ~/.composer/] ***************************************************
ok: [vccw.test]

TASK [Place a composer.json] ***************************************************
ok: [vccw.test]

TASK [Install Composer libraries] **********************************************
ok: [vccw.test] => (item=phpunit/phpunit:5.6)
ok: [vccw.test] => (item=squizlabs/php_codesniffer:~2.0)
ok: [vccw.test] => (item=wp-coding-standards/wpcs:*)

TASK [Install the WP-CLI] ******************************************************
ok: [vccw.test]

TASK [Create a ~/.wp-cli/] *****************************************************
ok: [vccw.test]

TASK [Install WP-CLI packages] *************************************************
changed: [vccw.test] => (item=https://github.com/vccw-team/wp-cli-scaffold-movefile/archive/master.zip)

TASK [Setup a bash completion for the WP-CLI] **********************************
ok: [vccw.test]

TASK [Create `wp-cli` dir] *****************************************************
ok: [vccw.test]

TASK [Place a `wp browse` command.] ********************************************
ok: [vccw.test]

TASK [Place a ~/.gemrc] ********************************************************
ok: [vccw.test]

TASK [Install Wordmove] ********************************************************
ok: [vccw.test]

TASK [Install Ruby gems] *******************************************************
ok: [vccw.test] => (item=bundler)
skipping: [vccw.test] => (item=wordmove)

TASK [Place a ~/.npmrc] ********************************************************
ok: [vccw.test]

TASK [Install npm packages] ****************************************************

TASK [Check the `phpcs` exists.] ***********************************************
changed: [vccw.test]

TASK [Setup the WordPress coding standard] *************************************
changed: [vccw.test]

TASK [Checkout the WordPress i18n Tools] ***************************************
ok: [vccw.test]

TASK [Remove unused files if exists] *******************************************
ok: [vccw.test] => (item=.wget-hsts)

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [vccw.test]

TASK [Allow remote connections to MySQL] ***************************************
ok: [vccw.test]

TASK [Place ~/.my.cnf] *********************************************************
ok: [vccw.test]

TASK [Create SSL dir] **********************************************************
ok: [vccw.test]

TASK [Create SSL keys] *********************************************************
changed: [vccw.test]

TASK [Replacing the Apache User] ***********************************************
ok: [vccw.test]

TASK [Replacing the Apache Group] **********************************************
ok: [vccw.test]

TASK [Place /etc/apache2/sites-available/site.conf] ****************************
ok: [vccw.test]

TASK [Disable keepalive] *******************************************************
ok: [vccw.test]

TASK [Setup timeout] ***********************************************************
ok: [vccw.test]

TASK [Enable virtual host for WordPress] ***************************************
changed: [vccw.test]

TASK [Update php.ini] **********************************************************
ok: [vccw.test] => (item={'value': False, 'key': u'short_open_tag'})
ok: [vccw.test] => (item={'value': u'1024M', 'key': u'upload_max_filesize'})
ok: [vccw.test] => (item={'value': u'neutral', 'key': u'mbstring.language'})
ok: [vccw.test] => (item={'value': u'UTC', 'key': u'date.timezone'})
ok: [vccw.test] => (item={'value': True, 'key': u'xdebug.remote_enable'})
ok: [vccw.test] => (item={'value': 9000, 'key': u'xdebug.remote_port'})
ok: [vccw.test] => (item={'value': u'UTF-8', 'key': u'default_charset'})
ok: [vccw.test] => (item={'value': True, 'key': u'xdebug.remote_connect_back'})
ok: [vccw.test] => (item={'value': u'VCCWDEBUG', 'key': u'xdebug.idekey'})
ok: [vccw.test] => (item={'value': True, 'key': u'xdebug.remote_autostart'})
ok: [vccw.test] => (item={'value': True, 'key': u'xdebug.profiler_enable'})
ok: [vccw.test] => (item={'value': u'UTF-8', 'key': u'mbstring.internal_encoding'})
ok: [vccw.test] => (item={'value': u'/tmp', 'key': u'session.save_path'})
ok: [vccw.test] => (item={'value': u'127.0.0.1', 'key': u'xdebug.remote_host'})
ok: [vccw.test] => (item={'value': u'1024M', 'key': u'post_max_size'})

TASK [Update php.ini for cli] **************************************************
ok: [vccw.test] => (item={'value': False, 'key': u'short_open_tag'})
ok: [vccw.test] => (item={'value': u'1024M', 'key': u'upload_max_filesize'})
ok: [vccw.test] => (item={'value': u'neutral', 'key': u'mbstring.language'})
ok: [vccw.test] => (item={'value': u'UTC', 'key': u'date.timezone'})
ok: [vccw.test] => (item={'value': True, 'key': u'xdebug.remote_enable'})
ok: [vccw.test] => (item={'value': 9000, 'key': u'xdebug.remote_port'})
ok: [vccw.test] => (item={'value': u'UTF-8', 'key': u'default_charset'})
ok: [vccw.test] => (item={'value': True, 'key': u'xdebug.remote_connect_back'})
ok: [vccw.test] => (item={'value': u'VCCWDEBUG', 'key': u'xdebug.idekey'})
ok: [vccw.test] => (item={'value': True, 'key': u'xdebug.remote_autostart'})
ok: [vccw.test] => (item={'value': True, 'key': u'xdebug.profiler_enable'})
ok: [vccw.test] => (item={'value': u'UTF-8', 'key': u'mbstring.internal_encoding'})
ok: [vccw.test] => (item={'value': u'/tmp', 'key': u'session.save_path'})
ok: [vccw.test] => (item={'value': u'127.0.0.1', 'key': u'xdebug.remote_host'})
ok: [vccw.test] => (item={'value': u'1024M', 'key': u'post_max_size'})

TASK [Install mailcatcher] *****************************************************
ok: [vccw.test]

TASK [Add mailcatcher to service] **********************************************
ok: [vccw.test]

TASK [Start mailcatcher] *******************************************************
ok: [vccw.test]

TASK [Update php.ini for mailcatcher] ******************************************
ok: [vccw.test]

TASK [Update php.ini for mailcatcher for cli] **********************************
ok: [vccw.test]

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [vccw.test]

TASK [Create Database] *********************************************************
ok: [vccw.test]

TASK [Create MySQL user] *******************************************************
ok: [vccw.test]

TASK [Change owner of the /var/www/html/] **************************************
ok: [vccw.test]

TASK [Remove index.html from document root] ************************************
ok: [vccw.test]

TASK [Run `wp core download`] **************************************************
changed: [vccw.test]

TASK [Create temporary file for extra-php in wp-config.php] ********************
ok: [vccw.test]

TASK [Run `wp core config`] ****************************************************
changed: [vccw.test]

TASK [Run `wp db reset`] *******************************************************
changed: [vccw.test]

TASK [Run `wp core install`] ***************************************************
changed: [vccw.test]

TASK [Create index.php for wp_siteurl] *****************************************
skipping: [vccw.test]

TASK [Move index.php for wp_siteurl] *******************************************
skipping: [vccw.test]

TASK [stat] ********************************************************************
ok: [vccw.test]

TASK [Create `.gitignore`] *****************************************************
skipping: [vccw.test]

TASK [Move `.gitignore`] *******************************************************
skipping: [vccw.test]

TASK [Run `wp core language install`] ******************************************
changed: [vccw.test]

TASK [Run `wp plugin install`] *************************************************
changed: [vccw.test] => (item=logbook)

TASK [Run `wp plugin install wp-multibyte-patch`] ******************************
skipping: [vccw.test]

TASK [Run `wp theme install`] **************************************************
skipping: [vccw.test]

TASK [Install `wordpress-importer`] ********************************************
skipping: [vccw.test]

TASK [Download WordPress theme unit test data] *********************************
skipping: [vccw.test]

TASK [Import WordPress theme unit test data] ***********************************
skipping: [vccw.test]

TASK [Run `wp options update`] *************************************************
changed: [vccw.test] => (item={'value': u'Hello VCCW.', 'key': u'blogdescription'})

TASK [Get the timezone] ********************************************************
changed: [vccw.test]

TASK [Update timezone] *********************************************************
changed: [vccw.test]

TASK [Get the date format] *****************************************************
changed: [vccw.test]

TASK [Update date format] ******************************************************
changed: [vccw.test]

TASK [Run `wp rewrite structure`] **********************************************
changed: [vccw.test]

TASK [Flush rewrite rules] *****************************************************
changed: [vccw.test]

TASK [Run `wp core multisite-convert`] *****************************************
skipping: [vccw.test]

TASK [Create `.htaccess` for multisite] ****************************************
skipping: [vccw.test]

TASK [Move `.htaccess` for multisite] ******************************************
skipping: [vccw.test]

TASK [Setting up Wordpress multisite options] **********************************

TASK [Check `wp scaffold movefile` exists.] ************************************
changed: [vccw.test]

TASK [stat] ********************************************************************
ok: [vccw.test]

TASK [Create a Movefile] *******************************************************
ok: [vccw.test]

PLAY RECAP *********************************************************************
vccw.test                  : ok=64   changed=20   unreachable=0    failed=0

**Comment by miya0001** [comment]
Please check values of your `site.yml`.
I guess your value of `hostname` is incorrect or there is an virtual machine that has same IP address or hostname.

**Comment by JinZhenlin** [comment]
Thank you!

**Comment by JinZhenlin** [comment]
> Please check values of your `site.yml`.
> I guess your value of `hostname` is incorrect or there is an virtual machine that has same IP address or hostname.

Thanks a lot!
