### ISSUE TITLE
Mailcatcher is not working

### ISSUE THREAD

**Issue by luizbills** [vccw-team/vccw#346]
Operating System: Linux/Ubuntu 18.10
Vagrant Version: 2.2.3
Virtual Box Version: 6.0.4

---

My Mailcatcher is not working. Is there any log to diagnose this?

When I installed, in first time works. But after a second `vagrant up`, I can't access http://{myurl}:1080 and it gives a ERR_CONNECTION_REFUSED error in browser.

**Comment by lupusellobo** [comment]
The service is down by default. Just write `sudo service mailcatcher start` and everything whould work now

**Comment by luizbills** [comment]
@lupusellobo works. Thanks.

But how can I run that `service start` every time I boot my vm?

**Comment by luizbills** [comment]
I found something. You can create a `run-always.sh` to run commands after `vagrant up`.

**Comment by lupusellobo** [comment]
Is that done with a plugin? Im still a noob with vagrant

**Comment by luizbills** [comment]
@lupusellobo create a file named `run-always.sh` inside of your vwwc directory.

**Comment by luizbills** [comment]
Reload your vm after: `vagrant reload`

**Comment by lupusellobo** [comment]
Great! thanks for the tip

**Comment by luizbills** [comment]
you're welcome

**Comment by luizbills** [comment]
Mailcatcher is not receiving emails :disappointed:
