### ISSUE TITLE
site.yml ignored

### ISSUE THREAD

**Issue by pandabrand** [vccw-team/vccw#348]
Operating System: OSX 10.13.6
Vagrant Version: 2.2.1
Virtual Box Version: 5.2.22

I made a site.yml file and updated the hostname and aliases. When I run `vagrant up` those are ignored I would get an error complaining that I already had a machine named 'vccw.test'. When I changed those variables in default.yml `vagrant up` runs as expected.

**Comment by ck1981** [comment]
It sounds like you created site.yml in /provision, move site.yml to root ie the dir where the vagrantfile is, then try. Now your changes to site.yml should take effect and you should also not get the error (assuming you change the hostname, probably better to change the IP too).

**Comment by pandabrand** [comment]
Reading comprehension is vital, thanks.
