### ISSUE TITLE
WordPress importer and media uploader are not working. Version 2.9.0

### ISSUE THREAD

**Issue by rsdevigo** [vccw-team/vccw#72]
Hello,
My env is:
- Windows 8.1
- Vagrant 1.6.5
- Virtualbox 4.3.26
- VCCW version 2.9.0

And I do the provision withou any errors, but when I come to the wordpress admin interface and try do a upload, a error without message appears
```
file,jpg: An error occurred in the upload. Please try again later.
```

Help me ?

**Comment by miya0001** [comment]
Please write `127.0.0.1 wordpress.local` to hosts file.
Then go to `http://wordpress.local/`.

http://www.sysprobs.com/how-to-edit-host-file-in-windows-8-1-8

**Comment by drsounds** [comment]
It does still not work

**Comment by zfrankdesign** [comment]
Having the same issue with v2.19.0 Is this still a known issue?

**Comment by Ravneson** [comment]
Same issue here, attempted editing hosts but in win 10 I get the following error: ERR_CONNECTION_REFUSED.

**Comment by miya0001** [comment]
Please change hostname from wordpress.local to vccw.dev.
Then please try again.

**Comment by funkenstrahlen** [comment]
I just ran into this issue too. I could fix it by adding `vccw.dev` to my `/etc/hosts`.

**Comment by miya0001** [comment]
WordPress uploader requires AJAX, so the cause of the problem is cross origin policy.
