### ISSUE TITLE
Can't install vccw on windows7

### ISSUE THREAD

**Issue by rootion** [vccw-team/vccw#74]
Hello,

I am struggling to get this running on windows 7. I am posting it here because I have looked tutorials and read different resources but I don't manage to get it working.

Followed the steps here > http://vccw.cc/
I have added the vagrant-hostsupdater plugin and also the IP 192.168.33.10 in my hosts file.
But when browsing either http://vccw.dev/ or http://192.168.33.10/ and I get the message `This webpage is not available ERR_ICANN_NAME_COLLISION`

This is what I am getting when I run `vagrant up`: http://pastebin.com/jpTbfb36

Any ideas? Thanks in advance.

**Comment by miya0001** [comment]
1. Please uninstall vagrant-hostsupdater plugin.
2. Write `vccw.dev 192.168.33.10` to hosts file manually.
3. Run `vagrant destroy`
4. Run `vagrant up`

**Comment by rootion** [comment]
That worked. Thank you!

**Comment by rootion** [comment]
That worked. Thank you!
