### ISSUE TITLE
Symlynks not working

### ISSUE THREAD

**Issue by meglio** [vccw-team/vccw#78]
Tried to create a soft symlink inside www/wordpress to my plugin outside of the vagrant root folder, but virtualbox can't see it.

**Comment by miya0001** [comment]
Under the www/wordpress is a shared folder, so symlink may doesn't work.

**Comment by meglio** [comment]
Symlinks do work in shared folders, pls see Virtualbox documentation - a special configuration is needed when mounting the folder.

**Comment by miya0001** [comment]
Could you give me URL?

**Comment by meglio** [comment]
http://docs.vagrantup.com/v2/synced-folders/basic_usage.html

See section titled "Symbolink links"

**Comment by miya0001** [comment]
> but some host/guest combinations still do not work properly. 

Sorry I don't know how to enable symlinks and I ever used it in shared folders.
If you need symlinks support, please try yourself.

**Comment by meglio** [comment]
As you wish :) Simpler to switch to a different vagrant box.
