### ISSUE TITLE
Please add notes about all ssh/mysql users created

### ISSUE THREAD

**Issue by meglio** [vccw-team/vccw#80]
Could not find any notes on what users are created in unix and in MySQL:
- how to access mysql root
- what is the wordpress username/pass for mysql
- what is the vagrant ssh password

It can be googled and tried, but may I ask you to add this info to the documentation.

**Comment by clinoge** [comment]
Access vagrant:
```
$ vagrant ssh 
```
As for mysql as root, after aforementioned command you should issue

```
$ mysql -u root -p
```

Everything else is within lines 115 and 120 Vagrantfile
```
    :mysql => {
        :bind_address           => '0.0.0.0',
        :server_debian_password => 'wordpress',
        :server_root_password   => 'wordpress',
        :server_repl_password   => 'wordpress'
      },
```

Hope this solves your problem.

**Comment by meglio** [comment]
Yes it does. I'm proposed to add the passwords to the documentation - i.e. when I want to connect in my MySQL admin gui, not from console.

**Comment by ianrobertdouglas** [comment]
1+ for adding these details to the documentation, especially for non-developers, like me. I'm trying to get access to the database with a GUI MySQL client. Can you please tell me what the following values should be, to open a SSH tunnel? I've tried various permutations, but nothing is working. Maybe you can make it crystal clear. Thanks.

MySQL Host:
MySQL Username:
MySQL Password:
MySQL Port

SSH Host:
SSH Username:
SSH Password:
SSH Port:

**Comment by miya0001** [comment]
Sorry for poor documentation, I will update vccw.cc when I would have a time.
And I am hoping you will pull request to this repository. :)
