### ISSUE TITLE
Help I'm New to This

### ISSUE THREAD

**Issue by realph** [vccw-team/vccw#81]
So I'm using Vagrant and VirtualBox for the first time after coming from a MAMP environment and I had a few questions:

I've managed to get the Vagrant environment up and running, and my WordPress site is working at http://vccw.dev.

- Where is the database? Usually with MAMP I went to phpMyAdmin or used SequelPro on the Mac to create and edit databases.

- How do I view my local WordPress site on my iPhone over the same network? http://vccw.dev works great on my machine, but it doesn't work if I try to access the same url on my iPhone. I've also tried 192.168.33.10, with no luck.

- Are there any great guides on getting started with the Vagrant + Chef + WordPress environment?

Any help is appreciated. Thanks in advance!

**Comment by miya0001** [comment]
* Database is in the vagrant machine. Please see wp-config.php.
* You can use vagrant share. http://docs.vagrantup.com/v2/share/
* Sorry vccw.cc only. :)

**Comment by realph** [comment]
@miya0001 Thanks for this. I'm trying to add a new database to the vagrant machine, but it won't let me. Currently there's a `wordpress` database there. Do you know how can I add a new database?

**Comment by miya0001** [comment]
https://dev.mysql.com/doc/refman/5.5/en/create-database.html

**Comment by realph** [comment]
@miya0001 Sorry, I've always created databases using phpMyAdmin or GUI apps like Sequel Pro. Do I have to SSH into this vagrant box to do this? Sorry, I'm completely new to this method.

**Comment by miya0001** [comment]
Sorry I don't know your GUI apps, so I can't help about it.
But VCCW is opening MySQL Port, you should set IP address on your app.

**Comment by waviaei** [comment]
On Sequel Pro, when you make a "New Connection", use "SSH" tab.

MySQL Host: 127.0.0.1
Username: wordpress
password: wordpress
ポート：3306

SSH Host: 127.0.0.1
SSH User: vagrant
SSH Password: vagrant
SSH Port: 2222

**Comment by ianrobertdouglas** [comment]
@waviaei I get the following using those settings with Sequel Pro:

debug1: connect to address 127.0.0.1 port 2222: Connection refused
ssh: connect to host 127.0.0.1 port 2222: Connection refused

**Comment by ZCLMK** [comment]
hi, this works very nicely on ubuntu but, when I want to login (http://vccw.test/wp-login.php) where do I find my username and password?
