### ISSUE TITLE
php.ini upload_max_filesize is set to 2MBs

### ISSUE THREAD

**Issue by negativefix** [vccw-team/vccw#83]
Today I got upload_max_filesize error while installing a theme by uploading. After that I check php.ini and saw upload_max_filesize is set to 2 MBs. Isn't it a little low? I just wanted to report it.

**Comment by kimipooh** [comment]
Provisionally, I think that you had better set up  "php_value upload_max_filesize 10M" in .htaccess.

**Comment by routelastresort** [comment]
https://github.com/vccw-team/vccw/pull/92

**Comment by miya0001** [comment]
:smile:
