### ISSUE TITLE
Wordmove pushing database error

### ISSUE THREAD

**Issue by rgantree** [vccw-team/vccw#85]
Hi there,

I cd to my project folder where the Movefile is
I run: word move push -all 
everything run fine, apart from Pushing Database:
I get the error below:
local | mysqldump --host=localhost --user=wordpress --password=wordpress wordpress > /Users/user/myproject/www/wordpress/wp-content/dump.sql
sh: mysqldump: command not found
/Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:147:in `run': Return code reports an error (RuntimeError)

can someone help with this please

Thanks

**Comment by flurinduerst** [comment]
I'm having the exact same problem. Were you able to fix it?
