### ISSUE TITLE
Problems with wp-admin, frontend

### ISSUE THREAD

**Issue by ianrobertdouglas** [vccw-team/vccw#86]
I tried importing an existing database, overwriting the "wordpress" database. When I go to http://vccw.dev, the frontend works, though there is a large space above my content (and a smaller space below it). Odd. But if I go to http://vccw.dev/wp-admin, I get the following:

![image](https://cloud.githubusercontent.com/assets/1595541/9808891/c8465fe4-5863-11e5-9a0b-2a3d2b0e659a.png)

**Comment by miya0001** [comment]
WordPress on VCCW is running with Debug Mode.
https://codex.wordpress.org/Debugging_in_WordPress

It is a problem of `wpfw_menus_management` plugin.

**Comment by ianrobertdouglas** [comment]
Thanks. Changing Debug Mode to "false" in /wp-config.php resolved both issues.
