### ISSUE TITLE
Automatically start Mailcather when vagrant up

### ISSUE THREAD

**Issue by mineralwassermedium** [vccw-team/vccw#88]
Hi
is there a way to startup mailcatcher automatically when I vagrant up?

**Comment by miya0001** [comment]
I am thinking it will come in next version, please wait. :smile:

**Comment by marushu** [comment]
Hi
I use this from host. ↓↓ :smile: 
cd path/to/site,yml directory
$ IP=`grep "ip:" site.yml | tr -d "ip: "`; vagrant ssh -c "mailcatcher --http-ip ${IP}"
