### ISSUE TITLE
Db always resetted on provision

### ISSUE THREAD

**Issue by nonameolsson** [vccw-team/vccw#91]
I really like VCCW! Good job!

I'm trying to custumize the provisioning. I have copied `provision/site.yml` to `site.yml` and it works. When I add plugins and provision the machine they're installed. Works great!
But when I change `reset_db_on_provision: true` to `false` in my `site.yml` the database is still resetted on provision.

Is there anything that I might be doing wrong?

**Comment by miya0001** [comment]
Oh.. Thanks, I will try to find it.

**Comment by nonameolsson** [comment]
Thanks, that would be great! We've started to use this Vagrant box at work. Really appreciate your help.

**Comment by torounit** [comment]
@nonameolsson 

Fixed the bug in c345d46c6769e0181743b951f238ba54ec61ce57 .
Please try master branch.
