### ISSUE TITLE
PHP 7.0.x support

### ISSUE THREAD

**Issue by pdefreitas** [vccw-team/vccw#93]
It would be nice if there was PHP 7 support since it is very fast and it is already stable.

**Comment by joeldrapper** [comment]
:+1:

**Comment by miya0001** [comment]
I tried like following,

site.yml:
```
php_version: 7.0.1
```

But apache module was not compiled... :cry: 
I am thinking we should change CentOS to Ubuntu.

Please wait, we will fix it. :smile:

**Comment by schmitzoide** [comment]
I have compiled some instructions on how to do this manually.
http://schmitzoi.de/installing-php7-on-a-vccw-vagrant-environment-with-centos-6-x/

Trying to add this to my fork, will present a pull request as soon as I am ready.

**Comment by imamassi** [comment]
One month later...

**Comment by schmitzoide** [comment]
@imamassi do it yourself, this is open source :-)

**Comment by brazitec** [comment]
the above link is broken..

**Comment by flurinduerst** [comment]
any news on this? :)

**Comment by dnagyelek** [comment]
nope
