### ISSUE TITLE
Errors / trouble provisioning vccw instance with modified hostname

### ISSUE THREAD

**Issue by Narthur** [vccw-team/vccw#99]
I need to have multiple separate vccw instances for different projects. I discovered that to avoid vagrant giving an error because two boxes are named the same, I have to create a `site.yml` file with a different value for `hostname`. So far so good.

However, when running `vagrant up` for the first time, one or more of the following errors:

> Chef never successfully completed! Any errors should be visible in the\noutput above. Please fix your recipes so that they properly complete.

And:

> Guest-specific operations were attempted on a machine that is not ready for guest communication. This should not happen and a bug should be reported.

Additionally, `ssh`ing into the machine sometimes reveals that the `var/www/wordpress` folder is empty. This isn't the case all the time.

Attempting to access the website at the hostname specified in the `site.yml` file produces the error "The requested URL / was not found on this server." even when WordPress appears to have been successfully installed at `var/www/wordpress`.

[Here is one debug log](https://gist.github.com/Narthur/8dbb3d255dba96b74c01).

What am I doing wrong? Is there a better way to avoid conflicts with multiple machines based on the vccw box?

**Comment by Narthur** [comment]
Here's the complete config:
https://github.com/OuachitaHillsMinistries/wp-oh-theme-vagrant

**Comment by miya0001** [comment]
I tried your vagrant and it looks working fine.

Following is my environment.

* VirtualBox: Version 5.0.14 r105127 (latest version)
* Vagrant: 1.8.1 (latest version)

**Comment by Narthur** [comment]
Thanks for checking it out. Not sure how to figure out what's going on, but I appreciate you taking a look at it.
